<?php
namespace CloudBeds\Aws\MskFork\LookoutforVision;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **Amazon Lookout for Vision** service.
 * @method \CloudBeds\Aws\MskFork\Result createDataset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createDatasetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createProject(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createProjectAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteDataset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDatasetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteProject(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteProjectAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeDataset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDatasetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeModelPackagingJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeModelPackagingJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeProject(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeProjectAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result detectAnomalies(array $args = [])
 * @method \GuzzleHttp\Promise\Promise detectAnomaliesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDatasetEntries(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDatasetEntriesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listModelPackagingJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listModelPackagingJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listModels(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listModelsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listProjects(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listProjectsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startModelPackagingJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startModelPackagingJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateDatasetEntries(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateDatasetEntriesAsync(array $args = [])
 */
class LookoutforVisionClient extends AwsClient {}
