<?php
namespace CloudBeds\Aws\MskFork\ConnectCampaignService;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AmazonConnectCampaignService** service.
 * @method \CloudBeds\Aws\MskFork\Result createCampaign(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createCampaignAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteCampaign(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteCampaignAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteConnectInstanceConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteConnectInstanceConfigAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteInstanceOnboardingJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteInstanceOnboardingJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeCampaign(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeCampaignAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getCampaignState(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getCampaignStateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getCampaignStateBatch(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getCampaignStateBatchAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getConnectInstanceConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getConnectInstanceConfigAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getInstanceOnboardingJobStatus(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getInstanceOnboardingJobStatusAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listCampaigns(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listCampaignsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result pauseCampaign(array $args = [])
 * @method \GuzzleHttp\Promise\Promise pauseCampaignAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putDialRequestBatch(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putDialRequestBatchAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result resumeCampaign(array $args = [])
 * @method \GuzzleHttp\Promise\Promise resumeCampaignAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startCampaign(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startCampaignAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startInstanceOnboardingJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startInstanceOnboardingJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopCampaign(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopCampaignAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateCampaignDialerConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateCampaignDialerConfigAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateCampaignName(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateCampaignNameAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateCampaignOutboundCallConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateCampaignOutboundCallConfigAsync(array $args = [])
 */
class ConnectCampaignServiceClient extends AwsClient {}
