<?php
namespace CloudBeds\Aws\MskFork\IVSRealTime;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **Amazon Interactive Video Service RealTime** service.
 * @method \CloudBeds\Aws\MskFork\Result createEncoderConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createEncoderConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createParticipantToken(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createParticipantTokenAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createStage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createStageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createStorageConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createStorageConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteEncoderConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteEncoderConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteStage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteStageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteStorageConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteStorageConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result disconnectParticipant(array $args = [])
 * @method \GuzzleHttp\Promise\Promise disconnectParticipantAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getComposition(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getCompositionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getEncoderConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getEncoderConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getParticipant(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getParticipantAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getStage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getStageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getStageSession(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getStageSessionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getStorageConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getStorageConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listCompositions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listCompositionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listEncoderConfigurations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listEncoderConfigurationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listParticipantEvents(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listParticipantEventsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listParticipants(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listParticipantsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listStageSessions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listStageSessionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listStages(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listStagesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listStorageConfigurations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listStorageConfigurationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startComposition(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startCompositionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopComposition(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopCompositionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateStage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateStageAsync(array $args = [])
 */
class IVSRealTimeClient extends AwsClient {}
