<?php
namespace CloudBeds\Aws\MskFork\Sms;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS Server Migration Service** service.
 * @method \CloudBeds\Aws\MskFork\Result createApp(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAppAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createReplicationJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createReplicationJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteApp(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAppAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAppLaunchConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAppLaunchConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAppReplicationConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAppReplicationConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAppValidationConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAppValidationConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteReplicationJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteReplicationJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteServerCatalog(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteServerCatalogAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result disassociateConnector(array $args = [])
 * @method \GuzzleHttp\Promise\Promise disassociateConnectorAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result generateChangeSet(array $args = [])
 * @method \GuzzleHttp\Promise\Promise generateChangeSetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result generateTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise generateTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getApp(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAppAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAppLaunchConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAppLaunchConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAppReplicationConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAppReplicationConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAppValidationConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAppValidationConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAppValidationOutput(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAppValidationOutputAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getConnectors(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getConnectorsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getReplicationJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getReplicationJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getReplicationRuns(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getReplicationRunsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getServers(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getServersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result importAppCatalog(array $args = [])
 * @method \GuzzleHttp\Promise\Promise importAppCatalogAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result importServerCatalog(array $args = [])
 * @method \GuzzleHttp\Promise\Promise importServerCatalogAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result launchApp(array $args = [])
 * @method \GuzzleHttp\Promise\Promise launchAppAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listApps(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAppsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result notifyAppValidationOutput(array $args = [])
 * @method \GuzzleHttp\Promise\Promise notifyAppValidationOutputAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putAppLaunchConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putAppLaunchConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putAppReplicationConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putAppReplicationConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putAppValidationConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putAppValidationConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startAppReplication(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startAppReplicationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startOnDemandAppReplication(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startOnDemandAppReplicationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startOnDemandReplicationRun(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startOnDemandReplicationRunAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopAppReplication(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopAppReplicationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result terminateApp(array $args = [])
 * @method \GuzzleHttp\Promise\Promise terminateAppAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateApp(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAppAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateReplicationJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateReplicationJobAsync(array $args = [])
 */
class SmsClient extends AwsClient {}
