<?php
namespace CloudBeds\Aws\MskFork\CodeCatalyst;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **Amazon CodeCatalyst** service.
 * @method \CloudBeds\Aws\MskFork\Result createAccessToken(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAccessTokenAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createDevEnvironment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createDevEnvironmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createProject(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createProjectAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createSourceRepository(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createSourceRepositoryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createSourceRepositoryBranch(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createSourceRepositoryBranchAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAccessToken(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAccessTokenAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteDevEnvironment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDevEnvironmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteProject(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteProjectAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteSourceRepository(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSourceRepositoryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteSpace(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSpaceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getDevEnvironment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getDevEnvironmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getProject(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getProjectAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSourceRepository(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSourceRepositoryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSourceRepositoryCloneUrls(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSourceRepositoryCloneUrlsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSpace(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSpaceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSubscription(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSubscriptionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getUserDetails(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getUserDetailsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getWorkflow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getWorkflowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getWorkflowRun(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getWorkflowRunAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAccessTokens(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAccessTokensAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDevEnvironmentSessions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDevEnvironmentSessionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDevEnvironments(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDevEnvironmentsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listEventLogs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listEventLogsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listProjects(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listProjectsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listSourceRepositories(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSourceRepositoriesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listSourceRepositoryBranches(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSourceRepositoryBranchesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listSpaces(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSpacesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listWorkflowRuns(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listWorkflowRunsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listWorkflows(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listWorkflowsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startDevEnvironment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startDevEnvironmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startDevEnvironmentSession(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startDevEnvironmentSessionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startWorkflowRun(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startWorkflowRunAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopDevEnvironment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopDevEnvironmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopDevEnvironmentSession(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopDevEnvironmentSessionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateDevEnvironment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateDevEnvironmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateProject(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateProjectAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateSpace(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateSpaceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result verifySession(array $args = [])
 * @method \GuzzleHttp\Promise\Promise verifySessionAsync(array $args = [])
 */
class CodeCatalystClient extends AwsClient {}
