<?php
namespace CloudBeds\Aws\MskFork\IoTTwinMaker;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS IoT TwinMaker** service.
 * @method \CloudBeds\Aws\MskFork\Result batchPutPropertyValues(array $args = [])
 * @method \GuzzleHttp\Promise\Promise batchPutPropertyValuesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result cancelMetadataTransferJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise cancelMetadataTransferJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createComponentType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createComponentTypeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createEntity(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createEntityAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createMetadataTransferJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createMetadataTransferJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createScene(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createSceneAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createSyncJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createSyncJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createWorkspace(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createWorkspaceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteComponentType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteComponentTypeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteEntity(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteEntityAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteScene(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSceneAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteSyncJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSyncJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteWorkspace(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteWorkspaceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result executeQuery(array $args = [])
 * @method \GuzzleHttp\Promise\Promise executeQueryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getComponentType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getComponentTypeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getEntity(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getEntityAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getMetadataTransferJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getMetadataTransferJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getPricingPlan(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getPricingPlanAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getPropertyValue(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getPropertyValueAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getPropertyValueHistory(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getPropertyValueHistoryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getScene(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSceneAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSyncJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSyncJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getWorkspace(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getWorkspaceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listComponentTypes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listComponentTypesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listComponents(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listComponentsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listEntities(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listEntitiesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listMetadataTransferJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listMetadataTransferJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listProperties(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPropertiesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listScenes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listScenesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listSyncJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSyncJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listSyncResources(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSyncResourcesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listWorkspaces(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listWorkspacesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateComponentType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateComponentTypeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateEntity(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateEntityAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updatePricingPlan(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updatePricingPlanAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateScene(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateSceneAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateWorkspace(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateWorkspaceAsync(array $args = [])
 */
class IoTTwinMakerClient extends AwsClient {}
