<?php
namespace CloudBeds\Aws\MskFork\CloudWatchEvidently;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **Amazon CloudWatch Evidently** service.
 * @method \CloudBeds\Aws\MskFork\Result batchEvaluateFeature(array $args = [])
 * @method \GuzzleHttp\Promise\Promise batchEvaluateFeatureAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createExperiment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createExperimentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createFeature(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createFeatureAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createLaunch(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createLaunchAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createProject(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createProjectAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createSegment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createSegmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteExperiment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteExperimentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteFeature(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteFeatureAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteLaunch(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteLaunchAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteProject(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteProjectAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteSegment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSegmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result evaluateFeature(array $args = [])
 * @method \GuzzleHttp\Promise\Promise evaluateFeatureAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getExperiment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getExperimentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getExperimentResults(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getExperimentResultsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getFeature(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getFeatureAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getLaunch(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getLaunchAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getProject(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getProjectAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSegment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSegmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listExperiments(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listExperimentsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listFeatures(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listFeaturesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listLaunches(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listLaunchesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listProjects(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listProjectsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listSegmentReferences(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSegmentReferencesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listSegments(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSegmentsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putProjectEvents(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putProjectEventsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startExperiment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startExperimentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startLaunch(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startLaunchAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopExperiment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopExperimentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopLaunch(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopLaunchAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result testSegmentPattern(array $args = [])
 * @method \GuzzleHttp\Promise\Promise testSegmentPatternAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateExperiment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateExperimentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateFeature(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateFeatureAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateLaunch(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateLaunchAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateProject(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateProjectAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateProjectDataDelivery(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateProjectDataDeliveryAsync(array $args = [])
 */
class CloudWatchEvidentlyClient extends AwsClient {}
