<?php
namespace CloudBeds\Aws\MskFork\FinSpaceData;

use CloudBeds\Aws\MskFork\AwsClient;
use CloudBeds\Aws\MskFork\CommandInterface;
use Psr\Http\Message\RequestInterface;

/**
 * This client is used to interact with the **FinSpace Public API** service.
 * @method \CloudBeds\Aws\MskFork\Result associateUserToPermissionGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise associateUserToPermissionGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createChangeset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createChangesetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createDataView(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createDataViewAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createDataset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createDatasetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createPermissionGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createPermissionGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createUserAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteDataset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDatasetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deletePermissionGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deletePermissionGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result disableUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise disableUserAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result disassociateUserFromPermissionGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise disassociateUserFromPermissionGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result enableUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise enableUserAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getChangeset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getChangesetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getDataView(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getDataViewAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getDataset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getDatasetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getExternalDataViewAccessDetails(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getExternalDataViewAccessDetailsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getPermissionGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getPermissionGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getProgrammaticAccessCredentials(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getProgrammaticAccessCredentialsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getUserAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getWorkingLocation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getWorkingLocationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listChangesets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listChangesetsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDataViews(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDataViewsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDatasets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDatasetsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listPermissionGroups(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPermissionGroupsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listPermissionGroupsByUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPermissionGroupsByUserAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listUsers(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listUsersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listUsersByPermissionGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listUsersByPermissionGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result resetUserPassword(array $args = [])
 * @method \GuzzleHttp\Promise\Promise resetUserPasswordAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateChangeset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateChangesetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateDataset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateDatasetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updatePermissionGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updatePermissionGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateUserAsync(array $args = [])
 */
class FinSpaceDataClient extends AwsClient {}
