<?php
namespace CloudBeds\Aws\MskFork\MigrationHubOrchestrator;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS Migration Hub Orchestrator** service.
 * @method \CloudBeds\Aws\MskFork\Result createWorkflow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createWorkflowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createWorkflowStep(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createWorkflowStepAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createWorkflowStepGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createWorkflowStepGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteWorkflow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteWorkflowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteWorkflowStep(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteWorkflowStepAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteWorkflowStepGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteWorkflowStepGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getTemplateStep(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getTemplateStepAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getTemplateStepGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getTemplateStepGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getWorkflow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getWorkflowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getWorkflowStep(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getWorkflowStepAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getWorkflowStepGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getWorkflowStepGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listPlugins(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPluginsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTemplateStepGroups(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTemplateStepGroupsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTemplateSteps(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTemplateStepsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTemplates(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTemplatesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listWorkflowStepGroups(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listWorkflowStepGroupsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listWorkflowSteps(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listWorkflowStepsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listWorkflows(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listWorkflowsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result retryWorkflowStep(array $args = [])
 * @method \GuzzleHttp\Promise\Promise retryWorkflowStepAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startWorkflow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startWorkflowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopWorkflow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopWorkflowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateWorkflow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateWorkflowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateWorkflowStep(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateWorkflowStepAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateWorkflowStepGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateWorkflowStepGroupAsync(array $args = [])
 */
class MigrationHubOrchestratorClient extends AwsClient {}
