<?php
namespace CloudBeds\Aws\MskFork\TranscribeService;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **Amazon Transcribe Service** service.
 * @method \CloudBeds\Aws\MskFork\Result createCallAnalyticsCategory(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createCallAnalyticsCategoryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createLanguageModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createLanguageModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createMedicalVocabulary(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createMedicalVocabularyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createVocabulary(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createVocabularyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createVocabularyFilter(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createVocabularyFilterAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteCallAnalyticsCategory(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteCallAnalyticsCategoryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteCallAnalyticsJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteCallAnalyticsJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteLanguageModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteLanguageModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteMedicalScribeJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteMedicalScribeJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteMedicalTranscriptionJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteMedicalTranscriptionJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteMedicalVocabulary(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteMedicalVocabularyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteTranscriptionJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteTranscriptionJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteVocabulary(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteVocabularyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteVocabularyFilter(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteVocabularyFilterAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeLanguageModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeLanguageModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getCallAnalyticsCategory(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getCallAnalyticsCategoryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getCallAnalyticsJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getCallAnalyticsJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getMedicalScribeJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getMedicalScribeJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getMedicalTranscriptionJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getMedicalTranscriptionJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getMedicalVocabulary(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getMedicalVocabularyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getTranscriptionJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getTranscriptionJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getVocabulary(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getVocabularyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getVocabularyFilter(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getVocabularyFilterAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listCallAnalyticsCategories(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listCallAnalyticsCategoriesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listCallAnalyticsJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listCallAnalyticsJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listLanguageModels(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listLanguageModelsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listMedicalScribeJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listMedicalScribeJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listMedicalTranscriptionJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listMedicalTranscriptionJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listMedicalVocabularies(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listMedicalVocabulariesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTranscriptionJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTranscriptionJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listVocabularies(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listVocabulariesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listVocabularyFilters(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listVocabularyFiltersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startCallAnalyticsJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startCallAnalyticsJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startMedicalScribeJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startMedicalScribeJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startMedicalTranscriptionJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startMedicalTranscriptionJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startTranscriptionJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startTranscriptionJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateCallAnalyticsCategory(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateCallAnalyticsCategoryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateMedicalVocabulary(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateMedicalVocabularyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateVocabulary(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateVocabularyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateVocabularyFilter(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateVocabularyFilterAsync(array $args = [])
 */
class TranscribeServiceClient extends AwsClient {}
