<?php
namespace CloudBeds\Aws\MskFork\Amplify;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS Amplify** service.
 * @method \CloudBeds\Aws\MskFork\Result createApp(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAppAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createBackendEnvironment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createBackendEnvironmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createBranch(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createBranchAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createDeployment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createDeploymentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createDomainAssociation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createDomainAssociationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createWebhook(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createWebhookAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteApp(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAppAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteBackendEnvironment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteBackendEnvironmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteBranch(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteBranchAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteDomainAssociation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDomainAssociationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteWebhook(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteWebhookAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result generateAccessLogs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise generateAccessLogsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getApp(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAppAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getArtifactUrl(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getArtifactUrlAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getBackendEnvironment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getBackendEnvironmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getBranch(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getBranchAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getDomainAssociation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getDomainAssociationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getWebhook(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getWebhookAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listApps(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAppsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listArtifacts(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listArtifactsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listBackendEnvironments(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listBackendEnvironmentsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listBranches(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listBranchesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDomainAssociations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDomainAssociationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listWebhooks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listWebhooksAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startDeployment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startDeploymentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateApp(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAppAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateBranch(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateBranchAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateDomainAssociation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateDomainAssociationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateWebhook(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateWebhookAsync(array $args = [])
 */
class AmplifyClient extends AwsClient {}
