<?php
namespace CloudBeds\Aws\MskFork\AmplifyUIBuilder;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS Amplify UI Builder** service.
 * @method \CloudBeds\Aws\MskFork\Result createComponent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createComponentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createForm(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createFormAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createTheme(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createThemeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteComponent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteComponentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteForm(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteFormAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteTheme(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteThemeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result exchangeCodeForToken(array $args = [])
 * @method \GuzzleHttp\Promise\Promise exchangeCodeForTokenAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result exportComponents(array $args = [])
 * @method \GuzzleHttp\Promise\Promise exportComponentsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result exportForms(array $args = [])
 * @method \GuzzleHttp\Promise\Promise exportFormsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result exportThemes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise exportThemesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getCodegenJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getCodegenJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getComponent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getComponentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getForm(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getFormAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getMetadata(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getMetadataAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getTheme(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getThemeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listCodegenJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listCodegenJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listComponents(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listComponentsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listForms(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listFormsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listThemes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listThemesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putMetadataFlag(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putMetadataFlagAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result refreshToken(array $args = [])
 * @method \GuzzleHttp\Promise\Promise refreshTokenAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startCodegenJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startCodegenJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateComponent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateComponentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateForm(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateFormAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateTheme(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateThemeAsync(array $args = [])
 */
class AmplifyUIBuilderClient extends AwsClient {}
