<?php
namespace CloudBeds\Aws\MskFork\Outposts;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS Outposts** service.
 * @method \CloudBeds\Aws\MskFork\Result cancelOrder(array $args = [])
 * @method \GuzzleHttp\Promise\Promise cancelOrderAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createOrder(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createOrderAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createOutpost(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createOutpostAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createSite(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createSiteAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteOutpost(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteOutpostAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteSite(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSiteAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getCatalogItem(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getCatalogItemAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getConnection(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getConnectionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getOrder(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getOrderAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getOutpost(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getOutpostAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getOutpostInstanceTypes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getOutpostInstanceTypesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSite(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSiteAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSiteAddress(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSiteAddressAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAssets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAssetsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listCatalogItems(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listCatalogItemsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listOrders(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listOrdersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listOutposts(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listOutpostsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listSites(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSitesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startConnection(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startConnectionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateOutpost(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateOutpostAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateSite(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateSiteAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateSiteAddress(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateSiteAddressAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateSiteRackPhysicalProperties(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateSiteRackPhysicalPropertiesAsync(array $args = [])
 */
class OutpostsClient extends AwsClient {}
