<?php
namespace CloudBeds\Aws\MskFork\SSMIncidents;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS Systems Manager Incident Manager** service.
 * @method \CloudBeds\Aws\MskFork\Result batchGetIncidentFindings(array $args = [])
 * @method \GuzzleHttp\Promise\Promise batchGetIncidentFindingsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createReplicationSet(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createReplicationSetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createResponsePlan(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createResponsePlanAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createTimelineEvent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createTimelineEventAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteIncidentRecord(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteIncidentRecordAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteReplicationSet(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteReplicationSetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteResourcePolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteResourcePolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteResponsePlan(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteResponsePlanAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteTimelineEvent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteTimelineEventAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getIncidentRecord(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getIncidentRecordAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getReplicationSet(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getReplicationSetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getResourcePolicies(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getResourcePoliciesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getResponsePlan(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getResponsePlanAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getTimelineEvent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getTimelineEventAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listIncidentFindings(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listIncidentFindingsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listIncidentRecords(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listIncidentRecordsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listRelatedItems(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listRelatedItemsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listReplicationSets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listReplicationSetsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listResponsePlans(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listResponsePlansAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTimelineEvents(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTimelineEventsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putResourcePolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putResourcePolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startIncident(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startIncidentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateDeletionProtection(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateDeletionProtectionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateIncidentRecord(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateIncidentRecordAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateRelatedItems(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateRelatedItemsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateReplicationSet(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateReplicationSetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateResponsePlan(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateResponsePlanAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateTimelineEvent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateTimelineEventAsync(array $args = [])
 */
class SSMIncidentsClient extends AwsClient {}
