<?php
namespace CloudBeds\Aws\MskFork\FIS;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS Fault Injection Simulator** service.
 * @method \CloudBeds\Aws\MskFork\Result createExperimentTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createExperimentTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createTargetAccountConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createTargetAccountConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteExperimentTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteExperimentTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteTargetAccountConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteTargetAccountConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAction(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getActionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getExperiment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getExperimentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getExperimentTargetAccountConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getExperimentTargetAccountConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getExperimentTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getExperimentTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getTargetAccountConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getTargetAccountConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getTargetResourceType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getTargetResourceTypeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listActions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listActionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listExperimentResolvedTargets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listExperimentResolvedTargetsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listExperimentTargetAccountConfigurations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listExperimentTargetAccountConfigurationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listExperimentTemplates(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listExperimentTemplatesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listExperiments(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listExperimentsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTargetAccountConfigurations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTargetAccountConfigurationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTargetResourceTypes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTargetResourceTypesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startExperiment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startExperimentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopExperiment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopExperimentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateExperimentTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateExperimentTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateTargetAccountConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateTargetAccountConfigurationAsync(array $args = [])
 */
class FISClient extends AwsClient {}
