<?php
namespace CloudBeds\Aws\MskFork\DataExchange;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS Data Exchange** service.
 * @method \CloudBeds\Aws\MskFork\Result cancelJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise cancelJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createDataSet(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createDataSetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createEventAction(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createEventActionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createRevision(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createRevisionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAsset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAssetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteDataSet(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDataSetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteEventAction(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteEventActionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteRevision(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteRevisionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAsset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAssetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getDataSet(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getDataSetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getEventAction(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getEventActionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getRevision(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getRevisionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDataSetRevisions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDataSetRevisionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDataSets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDataSetsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listEventActions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listEventActionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listRevisionAssets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listRevisionAssetsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result revokeRevision(array $args = [])
 * @method \GuzzleHttp\Promise\Promise revokeRevisionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result sendApiAsset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise sendApiAssetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result sendDataSetNotification(array $args = [])
 * @method \GuzzleHttp\Promise\Promise sendDataSetNotificationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateAsset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAssetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateDataSet(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateDataSetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateEventAction(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateEventActionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateRevision(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateRevisionAsync(array $args = [])
 */
class DataExchangeClient extends AwsClient {}
