<?php
namespace CloudBeds\Aws\MskFork\KinesisVideo;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **Amazon Kinesis Video Streams** service.
 * @method \CloudBeds\Aws\MskFork\Result createSignalingChannel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createSignalingChannelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createStream(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createStreamAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteEdgeConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteEdgeConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteSignalingChannel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSignalingChannelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteStream(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteStreamAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeEdgeConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeEdgeConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeImageGenerationConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeImageGenerationConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeMappedResourceConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeMappedResourceConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeMediaStorageConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeMediaStorageConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeNotificationConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeNotificationConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeSignalingChannel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeSignalingChannelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeStream(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeStreamAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getDataEndpoint(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getDataEndpointAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSignalingChannelEndpoint(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSignalingChannelEndpointAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listEdgeAgentConfigurations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listEdgeAgentConfigurationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listSignalingChannels(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSignalingChannelsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listStreams(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listStreamsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForStream(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForStreamAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startEdgeConfigurationUpdate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startEdgeConfigurationUpdateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagStream(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagStreamAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagStream(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagStreamAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateDataRetention(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateDataRetentionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateImageGenerationConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateImageGenerationConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateMediaStorageConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateMediaStorageConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateNotificationConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateNotificationConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateSignalingChannel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateSignalingChannelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateStream(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateStreamAsync(array $args = [])
 */
class KinesisVideoClient extends AwsClient {}
