<?php
namespace CloudBeds\Aws\MskFork\AppFabric;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AppFabric** service.
 * @method \CloudBeds\Aws\MskFork\Result batchGetUserAccessTasks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise batchGetUserAccessTasksAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result connectAppAuthorization(array $args = [])
 * @method \GuzzleHttp\Promise\Promise connectAppAuthorizationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createAppAuthorization(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAppAuthorizationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createAppBundle(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAppBundleAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createIngestion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createIngestionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createIngestionDestination(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createIngestionDestinationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAppAuthorization(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAppAuthorizationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAppBundle(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAppBundleAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteIngestion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteIngestionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteIngestionDestination(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteIngestionDestinationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAppAuthorization(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAppAuthorizationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAppBundle(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAppBundleAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getIngestion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getIngestionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getIngestionDestination(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getIngestionDestinationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAppAuthorizations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAppAuthorizationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAppBundles(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAppBundlesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listIngestionDestinations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listIngestionDestinationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listIngestions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listIngestionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startIngestion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startIngestionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startUserAccessTasks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startUserAccessTasksAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopIngestion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopIngestionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateAppAuthorization(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAppAuthorizationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateIngestionDestination(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateIngestionDestinationAsync(array $args = [])
 */
class AppFabricClient extends AwsClient {}
