<?php
namespace CloudBeds\Aws\MskFork\finspace;

use CloudBeds\Aws\MskFork\AwsClient;
use CloudBeds\Aws\MskFork\CommandInterface;
use Psr\Http\Message\RequestInterface;

/**
 * This client is used to interact with the **FinSpace User Environment Management service** service.
 * @method \CloudBeds\Aws\MskFork\Result createEnvironment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createEnvironmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createKxChangeset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createKxChangesetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createKxCluster(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createKxClusterAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createKxDatabase(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createKxDatabaseAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createKxEnvironment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createKxEnvironmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createKxUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createKxUserAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteEnvironment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteEnvironmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteKxCluster(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteKxClusterAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteKxDatabase(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteKxDatabaseAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteKxEnvironment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteKxEnvironmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteKxUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteKxUserAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getEnvironment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getEnvironmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getKxChangeset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getKxChangesetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getKxCluster(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getKxClusterAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getKxConnectionString(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getKxConnectionStringAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getKxDatabase(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getKxDatabaseAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getKxEnvironment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getKxEnvironmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getKxUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getKxUserAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listEnvironments(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listEnvironmentsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listKxChangesets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listKxChangesetsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listKxClusterNodes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listKxClusterNodesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listKxClusters(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listKxClustersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listKxDatabases(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listKxDatabasesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listKxEnvironments(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listKxEnvironmentsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listKxUsers(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listKxUsersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateEnvironment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateEnvironmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateKxClusterCodeConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateKxClusterCodeConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateKxClusterDatabases(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateKxClusterDatabasesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateKxDatabase(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateKxDatabaseAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateKxEnvironment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateKxEnvironmentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateKxEnvironmentNetwork(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateKxEnvironmentNetworkAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateKxUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateKxUserAsync(array $args = [])
 */
class finspaceClient extends AwsClient {}
