<?php
namespace CloudBeds\Aws\MskFork\Swf;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * Amazon Simple Workflow Service (Amazon SWF) client.
 *
 * @method \CloudBeds\Aws\MskFork\Result countClosedWorkflowExecutions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise countClosedWorkflowExecutionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result countOpenWorkflowExecutions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise countOpenWorkflowExecutionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result countPendingActivityTasks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise countPendingActivityTasksAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result countPendingDecisionTasks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise countPendingDecisionTasksAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deprecateActivityType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deprecateActivityTypeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deprecateDomain(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deprecateDomainAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deprecateWorkflowType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deprecateWorkflowTypeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeActivityType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeActivityTypeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeDomain(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDomainAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeWorkflowExecution(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeWorkflowExecutionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeWorkflowType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeWorkflowTypeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getWorkflowExecutionHistory(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getWorkflowExecutionHistoryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listActivityTypes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listActivityTypesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listClosedWorkflowExecutions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listClosedWorkflowExecutionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDomains(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDomainsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listOpenWorkflowExecutions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listOpenWorkflowExecutionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listWorkflowTypes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listWorkflowTypesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result pollForActivityTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise pollForActivityTaskAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result pollForDecisionTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise pollForDecisionTaskAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result recordActivityTaskHeartbeat(array $args = [])
 * @method \GuzzleHttp\Promise\Promise recordActivityTaskHeartbeatAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result registerActivityType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise registerActivityTypeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result registerDomain(array $args = [])
 * @method \GuzzleHttp\Promise\Promise registerDomainAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result registerWorkflowType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise registerWorkflowTypeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result requestCancelWorkflowExecution(array $args = [])
 * @method \GuzzleHttp\Promise\Promise requestCancelWorkflowExecutionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result respondActivityTaskCanceled(array $args = [])
 * @method \GuzzleHttp\Promise\Promise respondActivityTaskCanceledAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result respondActivityTaskCompleted(array $args = [])
 * @method \GuzzleHttp\Promise\Promise respondActivityTaskCompletedAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result respondActivityTaskFailed(array $args = [])
 * @method \GuzzleHttp\Promise\Promise respondActivityTaskFailedAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result respondDecisionTaskCompleted(array $args = [])
 * @method \GuzzleHttp\Promise\Promise respondDecisionTaskCompletedAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result signalWorkflowExecution(array $args = [])
 * @method \GuzzleHttp\Promise\Promise signalWorkflowExecutionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startWorkflowExecution(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startWorkflowExecutionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result terminateWorkflowExecution(array $args = [])
 * @method \GuzzleHttp\Promise\Promise terminateWorkflowExecutionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result undeprecateActivityType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise undeprecateActivityTypeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result undeprecateDomain(array $args = [])
 * @method \GuzzleHttp\Promise\Promise undeprecateDomainAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result undeprecateWorkflowType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise undeprecateWorkflowTypeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 */
class SwfClient extends AwsClient {}
