<?php
namespace CloudBeds\Aws\MskFork\IoTEvents;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS IoT Events** service.
 * @method \CloudBeds\Aws\MskFork\Result createAlarmModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAlarmModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createDetectorModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createDetectorModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createInput(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createInputAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAlarmModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAlarmModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteDetectorModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDetectorModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteInput(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteInputAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeAlarmModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAlarmModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeDetectorModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDetectorModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeDetectorModelAnalysis(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDetectorModelAnalysisAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeInput(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeInputAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeLoggingOptions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeLoggingOptionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getDetectorModelAnalysisResults(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getDetectorModelAnalysisResultsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAlarmModelVersions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAlarmModelVersionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAlarmModels(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAlarmModelsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDetectorModelVersions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDetectorModelVersionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDetectorModels(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDetectorModelsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listInputRoutings(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listInputRoutingsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listInputs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listInputsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putLoggingOptions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putLoggingOptionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startDetectorModelAnalysis(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startDetectorModelAnalysisAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateAlarmModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAlarmModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateDetectorModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateDetectorModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateInput(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateInputAsync(array $args = [])
 */
class IoTEventsClient extends AwsClient {}
