<?php
namespace CloudBeds\Aws\MskFork\CleanRoomsML;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **cleanrooms-ml** service.
 * @method \CloudBeds\Aws\MskFork\Result createAudienceModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAudienceModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createConfiguredAudienceModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createConfiguredAudienceModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createTrainingDataset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createTrainingDatasetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAudienceGenerationJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAudienceGenerationJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAudienceModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAudienceModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteConfiguredAudienceModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteConfiguredAudienceModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteConfiguredAudienceModelPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteConfiguredAudienceModelPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteTrainingDataset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteTrainingDatasetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAudienceGenerationJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAudienceGenerationJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAudienceModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAudienceModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getConfiguredAudienceModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getConfiguredAudienceModelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getConfiguredAudienceModelPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getConfiguredAudienceModelPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getTrainingDataset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getTrainingDatasetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAudienceExportJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAudienceExportJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAudienceGenerationJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAudienceGenerationJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAudienceModels(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAudienceModelsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listConfiguredAudienceModels(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listConfiguredAudienceModelsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTrainingDatasets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTrainingDatasetsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putConfiguredAudienceModelPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putConfiguredAudienceModelPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startAudienceExportJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startAudienceExportJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startAudienceGenerationJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startAudienceGenerationJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateConfiguredAudienceModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateConfiguredAudienceModelAsync(array $args = [])
 */
class CleanRoomsMLClient extends AwsClient {}
