<?php
namespace CloudBeds\Aws\MskFork\BackupGateway;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS Backup Gateway** service.
 * @method \CloudBeds\Aws\MskFork\Result associateGatewayToServer(array $args = [])
 * @method \GuzzleHttp\Promise\Promise associateGatewayToServerAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createGateway(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createGatewayAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteGateway(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteGatewayAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteHypervisor(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteHypervisorAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result disassociateGatewayFromServer(array $args = [])
 * @method \GuzzleHttp\Promise\Promise disassociateGatewayFromServerAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getBandwidthRateLimitSchedule(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getBandwidthRateLimitScheduleAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getGateway(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getGatewayAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getHypervisor(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getHypervisorAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getHypervisorPropertyMappings(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getHypervisorPropertyMappingsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getVirtualMachine(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getVirtualMachineAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result importHypervisorConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise importHypervisorConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listGateways(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listGatewaysAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listHypervisors(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listHypervisorsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listVirtualMachines(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listVirtualMachinesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putBandwidthRateLimitSchedule(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putBandwidthRateLimitScheduleAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putHypervisorPropertyMappings(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putHypervisorPropertyMappingsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putMaintenanceStartTime(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putMaintenanceStartTimeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startVirtualMachinesMetadataSync(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startVirtualMachinesMetadataSyncAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result testHypervisorConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise testHypervisorConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateGatewayInformation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateGatewayInformationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateGatewaySoftwareNow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateGatewaySoftwareNowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateHypervisor(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateHypervisorAsync(array $args = [])
 */
class BackupGatewayClient extends AwsClient {}
