<?php
namespace CloudBeds\Aws\MskFork\PrivateNetworks;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS Private 5G** service.
 * @method \CloudBeds\Aws\MskFork\Result acknowledgeOrderReceipt(array $args = [])
 * @method \GuzzleHttp\Promise\Promise acknowledgeOrderReceiptAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result activateDeviceIdentifier(array $args = [])
 * @method \GuzzleHttp\Promise\Promise activateDeviceIdentifierAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result activateNetworkSite(array $args = [])
 * @method \GuzzleHttp\Promise\Promise activateNetworkSiteAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result configureAccessPoint(array $args = [])
 * @method \GuzzleHttp\Promise\Promise configureAccessPointAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createNetwork(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createNetworkAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createNetworkSite(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createNetworkSiteAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deactivateDeviceIdentifier(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deactivateDeviceIdentifierAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteNetwork(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteNetworkAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteNetworkSite(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteNetworkSiteAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getDeviceIdentifier(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getDeviceIdentifierAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getNetwork(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getNetworkAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getNetworkResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getNetworkResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getNetworkSite(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getNetworkSiteAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getOrder(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getOrderAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDeviceIdentifiers(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDeviceIdentifiersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listNetworkResources(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listNetworkResourcesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listNetworkSites(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listNetworkSitesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listNetworks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listNetworksAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listOrders(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listOrdersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result ping(array $args = [])
 * @method \GuzzleHttp\Promise\Promise pingAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startNetworkResourceUpdate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startNetworkResourceUpdateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateNetworkSite(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateNetworkSiteAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateNetworkSitePlan(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateNetworkSitePlanAsync(array $args = [])
 */
class PrivateNetworksClient extends AwsClient {}
