<?php
namespace CloudBeds\Aws\MskFork\IoTThingsGraph;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS IoT Things Graph** service.
 * @method \CloudBeds\Aws\MskFork\Result associateEntityToThing(array $args = [])
 * @method \GuzzleHttp\Promise\Promise associateEntityToThingAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createFlowTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createFlowTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createSystemInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createSystemInstanceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createSystemTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createSystemTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteFlowTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteFlowTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteNamespace(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteNamespaceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteSystemInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSystemInstanceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteSystemTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSystemTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deploySystemInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deploySystemInstanceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deprecateFlowTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deprecateFlowTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deprecateSystemTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deprecateSystemTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeNamespace(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeNamespaceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result dissociateEntityFromThing(array $args = [])
 * @method \GuzzleHttp\Promise\Promise dissociateEntityFromThingAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getEntities(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getEntitiesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getFlowTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getFlowTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getFlowTemplateRevisions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getFlowTemplateRevisionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getNamespaceDeletionStatus(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getNamespaceDeletionStatusAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSystemInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSystemInstanceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSystemTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSystemTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSystemTemplateRevisions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSystemTemplateRevisionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getUploadStatus(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getUploadStatusAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listFlowExecutionMessages(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listFlowExecutionMessagesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result searchEntities(array $args = [])
 * @method \GuzzleHttp\Promise\Promise searchEntitiesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result searchFlowExecutions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise searchFlowExecutionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result searchFlowTemplates(array $args = [])
 * @method \GuzzleHttp\Promise\Promise searchFlowTemplatesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result searchSystemInstances(array $args = [])
 * @method \GuzzleHttp\Promise\Promise searchSystemInstancesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result searchSystemTemplates(array $args = [])
 * @method \GuzzleHttp\Promise\Promise searchSystemTemplatesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result searchThings(array $args = [])
 * @method \GuzzleHttp\Promise\Promise searchThingsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result undeploySystemInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise undeploySystemInstanceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateFlowTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateFlowTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateSystemTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateSystemTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result uploadEntityDefinitions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise uploadEntityDefinitionsAsync(array $args = [])
 */
class IoTThingsGraphClient extends AwsClient {}
