<?php
namespace CloudBeds\Aws\MskFork\OpenSearchServerless;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **OpenSearch Service Serverless** service.
 * @method \CloudBeds\Aws\MskFork\Result batchGetCollection(array $args = [])
 * @method \GuzzleHttp\Promise\Promise batchGetCollectionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result batchGetEffectiveLifecyclePolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise batchGetEffectiveLifecyclePolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result batchGetLifecyclePolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise batchGetLifecyclePolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result batchGetVpcEndpoint(array $args = [])
 * @method \GuzzleHttp\Promise\Promise batchGetVpcEndpointAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createAccessPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAccessPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createCollection(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createCollectionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createLifecyclePolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createLifecyclePolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createSecurityConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createSecurityConfigAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createSecurityPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createSecurityPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createVpcEndpoint(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createVpcEndpointAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAccessPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAccessPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteCollection(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteCollectionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteLifecyclePolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteLifecyclePolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteSecurityConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSecurityConfigAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteSecurityPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSecurityPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteVpcEndpoint(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteVpcEndpointAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAccessPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAccessPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAccountSettings(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAccountSettingsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getPoliciesStats(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getPoliciesStatsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSecurityConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSecurityConfigAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSecurityPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSecurityPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAccessPolicies(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAccessPoliciesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listCollections(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listCollectionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listLifecyclePolicies(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listLifecyclePoliciesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listSecurityConfigs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSecurityConfigsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listSecurityPolicies(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSecurityPoliciesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listVpcEndpoints(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listVpcEndpointsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateAccessPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAccessPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateAccountSettings(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAccountSettingsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateCollection(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateCollectionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateLifecyclePolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateLifecyclePolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateSecurityConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateSecurityConfigAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateSecurityPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateSecurityPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateVpcEndpoint(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateVpcEndpointAsync(array $args = [])
 */
class OpenSearchServerlessClient extends AwsClient {}
