<?php
namespace CloudBeds\Aws\MskFork\RAM;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS Resource Access Manager** service.
 * @method \CloudBeds\Aws\MskFork\Result acceptResourceShareInvitation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise acceptResourceShareInvitationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result associateResourceShare(array $args = [])
 * @method \GuzzleHttp\Promise\Promise associateResourceShareAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result associateResourceSharePermission(array $args = [])
 * @method \GuzzleHttp\Promise\Promise associateResourceSharePermissionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createPermission(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createPermissionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createPermissionVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createPermissionVersionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createResourceShare(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createResourceShareAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deletePermission(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deletePermissionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deletePermissionVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deletePermissionVersionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteResourceShare(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteResourceShareAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result disassociateResourceShare(array $args = [])
 * @method \GuzzleHttp\Promise\Promise disassociateResourceShareAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result disassociateResourceSharePermission(array $args = [])
 * @method \GuzzleHttp\Promise\Promise disassociateResourceSharePermissionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result enableSharingWithAwsOrganization(array $args = [])
 * @method \GuzzleHttp\Promise\Promise enableSharingWithAwsOrganizationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getPermission(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getPermissionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getResourcePolicies(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getResourcePoliciesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getResourceShareAssociations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getResourceShareAssociationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getResourceShareInvitations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getResourceShareInvitationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getResourceShares(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getResourceSharesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listPendingInvitationResources(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPendingInvitationResourcesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listPermissionAssociations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPermissionAssociationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listPermissionVersions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPermissionVersionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listPermissions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPermissionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listPrincipals(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPrincipalsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listReplacePermissionAssociationsWork(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listReplacePermissionAssociationsWorkAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listResourceSharePermissions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listResourceSharePermissionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listResourceTypes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listResourceTypesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listResources(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listResourcesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result promotePermissionCreatedFromPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise promotePermissionCreatedFromPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result promoteResourceShareCreatedFromPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise promoteResourceShareCreatedFromPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result rejectResourceShareInvitation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise rejectResourceShareInvitationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result replacePermissionAssociations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise replacePermissionAssociationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result setDefaultPermissionVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise setDefaultPermissionVersionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateResourceShare(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateResourceShareAsync(array $args = [])
 */
class RAMClient extends AwsClient {}
