<?php
namespace CloudBeds\Aws\MskFork\NetworkFirewall;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS Network Firewall** service.
 * @method \CloudBeds\Aws\MskFork\Result associateFirewallPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise associateFirewallPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result associateSubnets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise associateSubnetsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createFirewall(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createFirewallAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createFirewallPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createFirewallPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createRuleGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createRuleGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createTLSInspectionConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createTLSInspectionConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteFirewall(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteFirewallAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteFirewallPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteFirewallPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteResourcePolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteResourcePolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteRuleGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteRuleGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteTLSInspectionConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteTLSInspectionConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeFirewall(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeFirewallAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeFirewallPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeFirewallPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeLoggingConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeLoggingConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeResourcePolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeResourcePolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeRuleGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeRuleGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeRuleGroupMetadata(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeRuleGroupMetadataAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeTLSInspectionConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeTLSInspectionConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result disassociateSubnets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise disassociateSubnetsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listFirewallPolicies(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listFirewallPoliciesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listFirewalls(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listFirewallsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listRuleGroups(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listRuleGroupsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTLSInspectionConfigurations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTLSInspectionConfigurationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putResourcePolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putResourcePolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateFirewallDeleteProtection(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateFirewallDeleteProtectionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateFirewallDescription(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateFirewallDescriptionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateFirewallEncryptionConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateFirewallEncryptionConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateFirewallPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateFirewallPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateFirewallPolicyChangeProtection(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateFirewallPolicyChangeProtectionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateLoggingConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateLoggingConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateRuleGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateRuleGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateSubnetChangeProtection(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateSubnetChangeProtectionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateTLSInspectionConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateTLSInspectionConfigurationAsync(array $args = [])
 */
class NetworkFirewallClient extends AwsClient {}
