<?php
namespace CloudBeds\Aws\MskFork\ApplicationInsights;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **Amazon CloudWatch Application Insights** service.
 * @method \CloudBeds\Aws\MskFork\Result addWorkload(array $args = [])
 * @method \GuzzleHttp\Promise\Promise addWorkloadAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createApplication(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createApplicationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createComponent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createComponentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createLogPattern(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createLogPatternAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteApplication(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteApplicationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteComponent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteComponentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteLogPattern(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteLogPatternAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeApplication(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeApplicationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeComponent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeComponentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeComponentConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeComponentConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeComponentConfigurationRecommendation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeComponentConfigurationRecommendationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeLogPattern(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeLogPatternAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeObservation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeObservationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeProblem(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeProblemAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeProblemObservations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeProblemObservationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeWorkload(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeWorkloadAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listApplications(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listApplicationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listComponents(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listComponentsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listConfigurationHistory(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listConfigurationHistoryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listLogPatternSets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listLogPatternSetsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listLogPatterns(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listLogPatternsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listProblems(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listProblemsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listWorkloads(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listWorkloadsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result removeWorkload(array $args = [])
 * @method \GuzzleHttp\Promise\Promise removeWorkloadAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateApplication(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateApplicationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateComponent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateComponentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateComponentConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateComponentConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateLogPattern(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateLogPatternAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateProblem(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateProblemAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateWorkload(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateWorkloadAsync(array $args = [])
 */
class ApplicationInsightsClient extends AwsClient {}
