<?php
namespace CloudBeds\Aws\MskFork\Panorama;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS Panorama** service.
 * @method \CloudBeds\Aws\MskFork\Result createApplicationInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createApplicationInstanceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createJobForDevices(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createJobForDevicesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createNodeFromTemplateJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createNodeFromTemplateJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createPackage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createPackageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createPackageImportJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createPackageImportJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteDevice(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDeviceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deletePackage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deletePackageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deregisterPackageVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deregisterPackageVersionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeApplicationInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeApplicationInstanceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeApplicationInstanceDetails(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeApplicationInstanceDetailsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeDevice(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDeviceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeDeviceJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDeviceJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeNode(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeNodeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeNodeFromTemplateJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeNodeFromTemplateJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describePackage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describePackageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describePackageImportJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describePackageImportJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describePackageVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describePackageVersionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listApplicationInstanceDependencies(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listApplicationInstanceDependenciesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listApplicationInstanceNodeInstances(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listApplicationInstanceNodeInstancesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listApplicationInstances(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listApplicationInstancesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDevices(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDevicesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDevicesJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDevicesJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listNodeFromTemplateJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listNodeFromTemplateJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listNodes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listNodesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listPackageImportJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPackageImportJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listPackages(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPackagesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result provisionDevice(array $args = [])
 * @method \GuzzleHttp\Promise\Promise provisionDeviceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result registerPackageVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise registerPackageVersionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result removeApplicationInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise removeApplicationInstanceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result signalApplicationInstanceNodeInstances(array $args = [])
 * @method \GuzzleHttp\Promise\Promise signalApplicationInstanceNodeInstancesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateDeviceMetadata(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateDeviceMetadataAsync(array $args = [])
 */
class PanoramaClient extends AwsClient {}
