<?php
namespace CloudBeds\Aws\MskFork\ComprehendMedical;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS Comprehend Medical** service.
 * @method \CloudBeds\Aws\MskFork\Result describeEntitiesDetectionV2Job(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeEntitiesDetectionV2JobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeICD10CMInferenceJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeICD10CMInferenceJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describePHIDetectionJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describePHIDetectionJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeRxNormInferenceJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeRxNormInferenceJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeSNOMEDCTInferenceJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeSNOMEDCTInferenceJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result detectEntities(array $args = [])
 * @method \GuzzleHttp\Promise\Promise detectEntitiesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result detectEntitiesV2(array $args = [])
 * @method \GuzzleHttp\Promise\Promise detectEntitiesV2Async(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result detectPHI(array $args = [])
 * @method \GuzzleHttp\Promise\Promise detectPHIAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result inferICD10CM(array $args = [])
 * @method \GuzzleHttp\Promise\Promise inferICD10CMAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result inferRxNorm(array $args = [])
 * @method \GuzzleHttp\Promise\Promise inferRxNormAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result inferSNOMEDCT(array $args = [])
 * @method \GuzzleHttp\Promise\Promise inferSNOMEDCTAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listEntitiesDetectionV2Jobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listEntitiesDetectionV2JobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listICD10CMInferenceJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listICD10CMInferenceJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listPHIDetectionJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPHIDetectionJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listRxNormInferenceJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listRxNormInferenceJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listSNOMEDCTInferenceJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSNOMEDCTInferenceJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startEntitiesDetectionV2Job(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startEntitiesDetectionV2JobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startICD10CMInferenceJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startICD10CMInferenceJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startPHIDetectionJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startPHIDetectionJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startRxNormInferenceJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startRxNormInferenceJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startSNOMEDCTInferenceJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startSNOMEDCTInferenceJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopEntitiesDetectionV2Job(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopEntitiesDetectionV2JobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopICD10CMInferenceJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopICD10CMInferenceJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopPHIDetectionJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopPHIDetectionJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopRxNormInferenceJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopRxNormInferenceJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopSNOMEDCTInferenceJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopSNOMEDCTInferenceJobAsync(array $args = [])
 */
class ComprehendMedicalClient extends AwsClient {}
