<?php
namespace CloudBeds\Aws\MskFork\EntityResolution;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS EntityResolution** service.
 * @method \CloudBeds\Aws\MskFork\Result createIdMappingWorkflow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createIdMappingWorkflowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createMatchingWorkflow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createMatchingWorkflowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createSchemaMapping(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createSchemaMappingAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteIdMappingWorkflow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteIdMappingWorkflowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteMatchingWorkflow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteMatchingWorkflowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteSchemaMapping(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSchemaMappingAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getIdMappingJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getIdMappingJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getIdMappingWorkflow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getIdMappingWorkflowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getMatchId(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getMatchIdAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getMatchingJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getMatchingJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getMatchingWorkflow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getMatchingWorkflowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getProviderService(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getProviderServiceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSchemaMapping(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSchemaMappingAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listIdMappingJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listIdMappingJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listIdMappingWorkflows(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listIdMappingWorkflowsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listMatchingJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listMatchingJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listMatchingWorkflows(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listMatchingWorkflowsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listProviderServices(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listProviderServicesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listSchemaMappings(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSchemaMappingsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startIdMappingJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startIdMappingJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startMatchingJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startMatchingJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateIdMappingWorkflow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateIdMappingWorkflowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateMatchingWorkflow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateMatchingWorkflowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateSchemaMapping(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateSchemaMappingAsync(array $args = [])
 */
class EntityResolutionClient extends AwsClient {}
