<?php
namespace CloudBeds\Aws\MskFork\PcaConnectorAd;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **PcaConnectorAd** service.
 * @method \CloudBeds\Aws\MskFork\Result createConnector(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createConnectorAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createDirectoryRegistration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createDirectoryRegistrationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createServicePrincipalName(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createServicePrincipalNameAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createTemplateGroupAccessControlEntry(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createTemplateGroupAccessControlEntryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteConnector(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteConnectorAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteDirectoryRegistration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDirectoryRegistrationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteServicePrincipalName(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteServicePrincipalNameAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteTemplateGroupAccessControlEntry(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteTemplateGroupAccessControlEntryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getConnector(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getConnectorAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getDirectoryRegistration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getDirectoryRegistrationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getServicePrincipalName(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getServicePrincipalNameAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getTemplateGroupAccessControlEntry(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getTemplateGroupAccessControlEntryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listConnectors(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listConnectorsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDirectoryRegistrations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDirectoryRegistrationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listServicePrincipalNames(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listServicePrincipalNamesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTemplateGroupAccessControlEntries(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTemplateGroupAccessControlEntriesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTemplates(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTemplatesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateTemplateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateTemplateGroupAccessControlEntry(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateTemplateGroupAccessControlEntryAsync(array $args = [])
 */
class PcaConnectorAdClient extends AwsClient {}
