<?php
namespace CloudBeds\Aws\MskFork\BedrockAgent;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **Agents for Amazon Bedrock** service.
 * @method \CloudBeds\Aws\MskFork\Result associateAgentKnowledgeBase(array $args = [])
 * @method \GuzzleHttp\Promise\Promise associateAgentKnowledgeBaseAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createAgent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAgentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createAgentActionGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAgentActionGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createAgentAlias(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAgentAliasAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createDataSource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createDataSourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createKnowledgeBase(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createKnowledgeBaseAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAgent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAgentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAgentActionGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAgentActionGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAgentAlias(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAgentAliasAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAgentVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAgentVersionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteDataSource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDataSourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteKnowledgeBase(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteKnowledgeBaseAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result disassociateAgentKnowledgeBase(array $args = [])
 * @method \GuzzleHttp\Promise\Promise disassociateAgentKnowledgeBaseAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAgent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAgentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAgentActionGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAgentActionGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAgentAlias(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAgentAliasAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAgentKnowledgeBase(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAgentKnowledgeBaseAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAgentVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAgentVersionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getDataSource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getDataSourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getIngestionJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getIngestionJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getKnowledgeBase(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getKnowledgeBaseAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAgentActionGroups(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAgentActionGroupsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAgentAliases(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAgentAliasesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAgentKnowledgeBases(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAgentKnowledgeBasesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAgentVersions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAgentVersionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAgents(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAgentsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDataSources(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDataSourcesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listIngestionJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listIngestionJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listKnowledgeBases(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listKnowledgeBasesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result prepareAgent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise prepareAgentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startIngestionJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startIngestionJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateAgent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAgentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateAgentActionGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAgentActionGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateAgentAlias(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAgentAliasAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateAgentKnowledgeBase(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAgentKnowledgeBaseAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateDataSource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateDataSourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateKnowledgeBase(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateKnowledgeBaseAsync(array $args = [])
 */
class BedrockAgentClient extends AwsClient {}
