<?php
namespace CloudBeds\Aws\MskFork\Route53RecoveryReadiness;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS Route53 Recovery Readiness** service.
 * @method \CloudBeds\Aws\MskFork\Result createCell(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createCellAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createCrossAccountAuthorization(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createCrossAccountAuthorizationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createReadinessCheck(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createReadinessCheckAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createRecoveryGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createRecoveryGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createResourceSet(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createResourceSetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteCell(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteCellAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteCrossAccountAuthorization(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteCrossAccountAuthorizationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteReadinessCheck(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteReadinessCheckAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteRecoveryGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteRecoveryGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteResourceSet(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteResourceSetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getArchitectureRecommendations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getArchitectureRecommendationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getCell(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getCellAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getCellReadinessSummary(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getCellReadinessSummaryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getReadinessCheck(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getReadinessCheckAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getReadinessCheckResourceStatus(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getReadinessCheckResourceStatusAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getReadinessCheckStatus(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getReadinessCheckStatusAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getRecoveryGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getRecoveryGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getRecoveryGroupReadinessSummary(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getRecoveryGroupReadinessSummaryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getResourceSet(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getResourceSetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listCells(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listCellsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listCrossAccountAuthorizations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listCrossAccountAuthorizationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listReadinessChecks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listReadinessChecksAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listRecoveryGroups(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listRecoveryGroupsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listResourceSets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listResourceSetsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listRules(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listRulesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResources(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourcesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateCell(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateCellAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateReadinessCheck(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateReadinessCheckAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateRecoveryGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateRecoveryGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateResourceSet(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateResourceSetAsync(array $args = [])
 */
class Route53RecoveryReadinessClient extends AwsClient {}
