<?php
namespace CloudBeds\Aws\MskFork\Appflow;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **Amazon Appflow** service.
 * @method \CloudBeds\Aws\MskFork\Result cancelFlowExecutions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise cancelFlowExecutionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createConnectorProfile(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createConnectorProfileAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createFlow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createFlowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteConnectorProfile(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteConnectorProfileAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteFlow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteFlowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeConnector(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeConnectorAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeConnectorEntity(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeConnectorEntityAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeConnectorProfiles(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeConnectorProfilesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeConnectors(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeConnectorsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeFlow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeFlowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeFlowExecutionRecords(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeFlowExecutionRecordsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listConnectorEntities(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listConnectorEntitiesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listConnectors(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listConnectorsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listFlows(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listFlowsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result registerConnector(array $args = [])
 * @method \GuzzleHttp\Promise\Promise registerConnectorAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result resetConnectorMetadataCache(array $args = [])
 * @method \GuzzleHttp\Promise\Promise resetConnectorMetadataCacheAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startFlow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startFlowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopFlow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopFlowAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result unregisterConnector(array $args = [])
 * @method \GuzzleHttp\Promise\Promise unregisterConnectorAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateConnectorProfile(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateConnectorProfileAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateConnectorRegistration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateConnectorRegistrationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateFlow(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateFlowAsync(array $args = [])
 */
class AppflowClient extends AwsClient {}
