<?php
namespace CloudBeds\Aws\MskFork\Tnb;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS Telco Network Builder** service.
 * @method \CloudBeds\Aws\MskFork\Result cancelSolNetworkOperation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise cancelSolNetworkOperationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createSolFunctionPackage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createSolFunctionPackageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createSolNetworkInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createSolNetworkInstanceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createSolNetworkPackage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createSolNetworkPackageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteSolFunctionPackage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSolFunctionPackageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteSolNetworkInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSolNetworkInstanceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteSolNetworkPackage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSolNetworkPackageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSolFunctionInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSolFunctionInstanceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSolFunctionPackage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSolFunctionPackageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSolFunctionPackageContent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSolFunctionPackageContentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSolFunctionPackageDescriptor(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSolFunctionPackageDescriptorAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSolNetworkInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSolNetworkInstanceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSolNetworkOperation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSolNetworkOperationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSolNetworkPackage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSolNetworkPackageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSolNetworkPackageContent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSolNetworkPackageContentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSolNetworkPackageDescriptor(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSolNetworkPackageDescriptorAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result instantiateSolNetworkInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise instantiateSolNetworkInstanceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listSolFunctionInstances(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSolFunctionInstancesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listSolFunctionPackages(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSolFunctionPackagesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listSolNetworkInstances(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSolNetworkInstancesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listSolNetworkOperations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSolNetworkOperationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listSolNetworkPackages(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSolNetworkPackagesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putSolFunctionPackageContent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putSolFunctionPackageContentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putSolNetworkPackageContent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putSolNetworkPackageContentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result terminateSolNetworkInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise terminateSolNetworkInstanceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateSolFunctionPackage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateSolFunctionPackageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateSolNetworkInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateSolNetworkInstanceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateSolNetworkPackage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateSolNetworkPackageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result validateSolFunctionPackageContent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise validateSolFunctionPackageContentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result validateSolNetworkPackageContent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise validateSolNetworkPackageContentAsync(array $args = [])
 */
class TnbClient extends AwsClient {}
