<?php
namespace CloudBeds\Aws\MskFork\CodeArtifact;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **CodeArtifact** service.
 * @method \CloudBeds\Aws\MskFork\Result associateExternalConnection(array $args = [])
 * @method \GuzzleHttp\Promise\Promise associateExternalConnectionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result copyPackageVersions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise copyPackageVersionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createDomain(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createDomainAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createRepository(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createRepositoryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteDomain(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDomainAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteDomainPermissionsPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDomainPermissionsPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deletePackage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deletePackageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deletePackageVersions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deletePackageVersionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteRepository(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteRepositoryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteRepositoryPermissionsPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteRepositoryPermissionsPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeDomain(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDomainAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describePackage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describePackageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describePackageVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describePackageVersionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeRepository(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeRepositoryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result disassociateExternalConnection(array $args = [])
 * @method \GuzzleHttp\Promise\Promise disassociateExternalConnectionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result disposePackageVersions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise disposePackageVersionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAuthorizationToken(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAuthorizationTokenAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getDomainPermissionsPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getDomainPermissionsPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getPackageVersionAsset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getPackageVersionAssetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getPackageVersionReadme(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getPackageVersionReadmeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getRepositoryEndpoint(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getRepositoryEndpointAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getRepositoryPermissionsPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getRepositoryPermissionsPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDomains(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDomainsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listPackageVersionAssets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPackageVersionAssetsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listPackageVersionDependencies(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPackageVersionDependenciesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listPackageVersions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPackageVersionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listPackages(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPackagesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listRepositories(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listRepositoriesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listRepositoriesInDomain(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listRepositoriesInDomainAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result publishPackageVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise publishPackageVersionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putDomainPermissionsPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putDomainPermissionsPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putPackageOriginConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putPackageOriginConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putRepositoryPermissionsPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putRepositoryPermissionsPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updatePackageVersionsStatus(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updatePackageVersionsStatusAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateRepository(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateRepositoryAsync(array $args = [])
 */
class CodeArtifactClient extends AwsClient {}
