<?php
namespace CloudBeds\Aws\MskFork\Sfn;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS Step Functions** service.
 * @method \CloudBeds\Aws\MskFork\Result createActivity(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createActivityAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createStateMachine(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createStateMachineAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createStateMachineAlias(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createStateMachineAliasAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteActivity(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteActivityAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteStateMachine(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteStateMachineAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteStateMachineAlias(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteStateMachineAliasAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteStateMachineVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteStateMachineVersionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeActivity(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeActivityAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeExecution(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeExecutionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeMapRun(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeMapRunAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeStateMachine(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeStateMachineAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeStateMachineAlias(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeStateMachineAliasAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeStateMachineForExecution(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeStateMachineForExecutionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getActivityTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getActivityTaskAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getExecutionHistory(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getExecutionHistoryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listActivities(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listActivitiesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listExecutions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listExecutionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listMapRuns(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listMapRunsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listStateMachineAliases(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listStateMachineAliasesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listStateMachineVersions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listStateMachineVersionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listStateMachines(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listStateMachinesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result publishStateMachineVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise publishStateMachineVersionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result redriveExecution(array $args = [])
 * @method \GuzzleHttp\Promise\Promise redriveExecutionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result sendTaskFailure(array $args = [])
 * @method \GuzzleHttp\Promise\Promise sendTaskFailureAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result sendTaskHeartbeat(array $args = [])
 * @method \GuzzleHttp\Promise\Promise sendTaskHeartbeatAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result sendTaskSuccess(array $args = [])
 * @method \GuzzleHttp\Promise\Promise sendTaskSuccessAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startExecution(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startExecutionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startSyncExecution(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startSyncExecutionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopExecution(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopExecutionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result testState(array $args = [])
 * @method \GuzzleHttp\Promise\Promise testStateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateMapRun(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateMapRunAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateStateMachine(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateStateMachineAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateStateMachineAlias(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateStateMachineAliasAsync(array $args = [])
 */
class SfnClient extends AwsClient {}
