<?php
namespace CloudBeds\Aws\MskFork\Detective;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **Amazon Detective** service.
 * @method \CloudBeds\Aws\MskFork\Result acceptInvitation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise acceptInvitationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result batchGetGraphMemberDatasources(array $args = [])
 * @method \GuzzleHttp\Promise\Promise batchGetGraphMemberDatasourcesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result batchGetMembershipDatasources(array $args = [])
 * @method \GuzzleHttp\Promise\Promise batchGetMembershipDatasourcesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createGraph(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createGraphAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createMembers(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createMembersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteGraph(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteGraphAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteMembers(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteMembersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeOrganizationConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeOrganizationConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result disableOrganizationAdminAccount(array $args = [])
 * @method \GuzzleHttp\Promise\Promise disableOrganizationAdminAccountAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result disassociateMembership(array $args = [])
 * @method \GuzzleHttp\Promise\Promise disassociateMembershipAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result enableOrganizationAdminAccount(array $args = [])
 * @method \GuzzleHttp\Promise\Promise enableOrganizationAdminAccountAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getInvestigation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getInvestigationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getMembers(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getMembersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDatasourcePackages(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDatasourcePackagesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listGraphs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listGraphsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listIndicators(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listIndicatorsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listInvestigations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listInvestigationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listInvitations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listInvitationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listMembers(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listMembersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listOrganizationAdminAccounts(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listOrganizationAdminAccountsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result rejectInvitation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise rejectInvitationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startInvestigation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startInvestigationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startMonitoringMember(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startMonitoringMemberAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateDatasourcePackages(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateDatasourcePackagesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateInvestigationState(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateInvestigationStateAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateOrganizationConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateOrganizationConfigurationAsync(array $args = [])
 */
class DetectiveClient extends AwsClient {}
