<?php
namespace CloudBeds\Aws\MskFork\Budgets;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS Budgets** service.
 * @method \CloudBeds\Aws\MskFork\Result createBudget(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createBudgetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createBudgetAction(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createBudgetActionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createNotification(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createNotificationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createSubscriber(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createSubscriberAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteBudget(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteBudgetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteBudgetAction(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteBudgetActionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteNotification(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteNotificationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteSubscriber(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSubscriberAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeBudget(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBudgetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeBudgetAction(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBudgetActionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeBudgetActionHistories(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBudgetActionHistoriesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeBudgetActionsForAccount(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBudgetActionsForAccountAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeBudgetActionsForBudget(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBudgetActionsForBudgetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeBudgetNotificationsForAccount(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBudgetNotificationsForAccountAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeBudgetPerformanceHistory(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBudgetPerformanceHistoryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeBudgets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBudgetsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeNotificationsForBudget(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeNotificationsForBudgetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeSubscribersForNotification(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeSubscribersForNotificationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result executeBudgetAction(array $args = [])
 * @method \GuzzleHttp\Promise\Promise executeBudgetActionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateBudget(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateBudgetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateBudgetAction(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateBudgetActionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateNotification(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateNotificationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateSubscriber(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateSubscriberAsync(array $args = [])
 */
class BudgetsClient extends AwsClient {}
