<?php
namespace CloudBeds\Aws\MskFork\MQ;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AmazonMQ** service.
 * @method \CloudBeds\Aws\MskFork\Result createBroker(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createBrokerAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createTags(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createTagsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createUserAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteBroker(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteBrokerAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteTags(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteTagsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteUserAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeBroker(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBrokerAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeBrokerEngineTypes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBrokerEngineTypesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeBrokerInstanceOptions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBrokerInstanceOptionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeConfigurationRevision(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeConfigurationRevisionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeUserAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listBrokers(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listBrokersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listConfigurationRevisions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listConfigurationRevisionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listConfigurations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listConfigurationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTags(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listUsers(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listUsersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result promote(array $args = [])
 * @method \GuzzleHttp\Promise\Promise promoteAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result rebootBroker(array $args = [])
 * @method \GuzzleHttp\Promise\Promise rebootBrokerAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateBroker(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateBrokerAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateUserAsync(array $args = [])
 */
class MQClient extends AwsClient {}
