<?php
namespace CloudBeds\Aws\MskFork\FMS;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **Firewall Management Service** service.
 * @method \CloudBeds\Aws\MskFork\Result associateAdminAccount(array $args = [])
 * @method \GuzzleHttp\Promise\Promise associateAdminAccountAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result associateThirdPartyFirewall(array $args = [])
 * @method \GuzzleHttp\Promise\Promise associateThirdPartyFirewallAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result batchAssociateResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise batchAssociateResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result batchDisassociateResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise batchDisassociateResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAppsList(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAppsListAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteNotificationChannel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteNotificationChannelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deletePolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deletePolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteProtocolsList(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteProtocolsListAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteResourceSet(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteResourceSetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result disassociateAdminAccount(array $args = [])
 * @method \GuzzleHttp\Promise\Promise disassociateAdminAccountAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result disassociateThirdPartyFirewall(array $args = [])
 * @method \GuzzleHttp\Promise\Promise disassociateThirdPartyFirewallAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAdminAccount(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAdminAccountAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAdminScope(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAdminScopeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAppsList(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAppsListAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getComplianceDetail(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getComplianceDetailAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getNotificationChannel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getNotificationChannelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getProtectionStatus(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getProtectionStatusAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getProtocolsList(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getProtocolsListAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getResourceSet(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getResourceSetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getThirdPartyFirewallAssociationStatus(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getThirdPartyFirewallAssociationStatusAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getViolationDetails(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getViolationDetailsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAdminAccountsForOrganization(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAdminAccountsForOrganizationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAdminsManagingAccount(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAdminsManagingAccountAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAppsLists(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAppsListsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listComplianceStatus(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listComplianceStatusAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDiscoveredResources(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDiscoveredResourcesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listMemberAccounts(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listMemberAccountsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listPolicies(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPoliciesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listProtocolsLists(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listProtocolsListsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listResourceSetResources(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listResourceSetResourcesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listResourceSets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listResourceSetsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listThirdPartyFirewallFirewallPolicies(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listThirdPartyFirewallFirewallPoliciesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putAdminAccount(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putAdminAccountAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putAppsList(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putAppsListAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putNotificationChannel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putNotificationChannelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putPolicyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putProtocolsList(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putProtocolsListAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putResourceSet(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putResourceSetAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 */
class FMSClient extends AwsClient {}
