<?php
namespace CloudBeds\Aws\MskFork\Textract;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **Amazon Textract** service.
 * @method \CloudBeds\Aws\MskFork\Result analyzeDocument(array $args = [])
 * @method \GuzzleHttp\Promise\Promise analyzeDocumentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result analyzeExpense(array $args = [])
 * @method \GuzzleHttp\Promise\Promise analyzeExpenseAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result analyzeID(array $args = [])
 * @method \GuzzleHttp\Promise\Promise analyzeIDAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createAdapter(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAdapterAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createAdapterVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAdapterVersionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAdapter(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAdapterAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAdapterVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAdapterVersionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result detectDocumentText(array $args = [])
 * @method \GuzzleHttp\Promise\Promise detectDocumentTextAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAdapter(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAdapterAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAdapterVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAdapterVersionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getDocumentAnalysis(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getDocumentAnalysisAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getDocumentTextDetection(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getDocumentTextDetectionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getExpenseAnalysis(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getExpenseAnalysisAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getLendingAnalysis(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getLendingAnalysisAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getLendingAnalysisSummary(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getLendingAnalysisSummaryAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAdapterVersions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAdapterVersionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAdapters(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAdaptersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startDocumentAnalysis(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startDocumentAnalysisAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startDocumentTextDetection(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startDocumentTextDetectionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startExpenseAnalysis(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startExpenseAnalysisAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startLendingAnalysis(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startLendingAnalysisAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateAdapter(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAdapterAsync(array $args = [])
 */
class TextractClient extends AwsClient {}
