<?php
namespace CloudBeds\Aws\MskFork\GroundStation;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AWS Ground Station** service.
 * @method \CloudBeds\Aws\MskFork\Result cancelContact(array $args = [])
 * @method \GuzzleHttp\Promise\Promise cancelContactAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createConfigAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createDataflowEndpointGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createDataflowEndpointGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createEphemeris(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createEphemerisAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createMissionProfile(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createMissionProfileAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteConfigAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteDataflowEndpointGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDataflowEndpointGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteEphemeris(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteEphemerisAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteMissionProfile(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteMissionProfileAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeContact(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeContactAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeEphemeris(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeEphemerisAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAgentConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAgentConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getMissionProfileConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getMissionProfileConfigAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getDataflowEndpointGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getDataflowEndpointGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getMinuteUsage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getMinuteUsageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getMissionProfile(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getMissionProfileAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getSatellite(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSatelliteAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listConfigs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listConfigsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listContacts(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listContactsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDataflowEndpointGroups(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDataflowEndpointGroupsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listEphemerides(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listEphemeridesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listGroundStations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listGroundStationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listMissionProfiles(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listMissionProfilesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listSatellites(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSatellitesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result registerAgent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise registerAgentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result reserveContact(array $args = [])
 * @method \GuzzleHttp\Promise\Promise reserveContactAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateAgentStatus(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAgentStatusAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateConfigAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateEphemeris(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateEphemerisAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateMissionProfile(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateMissionProfileAsync(array $args = [])
 */
class GroundStationClient extends AwsClient {}
