<?php
namespace CloudBeds\Aws\MskFork\IVS;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **Amazon Interactive Video Service** service.
 * @method \CloudBeds\Aws\MskFork\Result batchGetChannel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise batchGetChannelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result batchGetStreamKey(array $args = [])
 * @method \GuzzleHttp\Promise\Promise batchGetStreamKeyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result batchStartViewerSessionRevocation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise batchStartViewerSessionRevocationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createChannel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createChannelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createRecordingConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createRecordingConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createStreamKey(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createStreamKeyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteChannel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteChannelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deletePlaybackKeyPair(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deletePlaybackKeyPairAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteRecordingConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteRecordingConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteStreamKey(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteStreamKeyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getChannel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getChannelAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getPlaybackKeyPair(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getPlaybackKeyPairAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getRecordingConfiguration(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getRecordingConfigurationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getStream(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getStreamAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getStreamKey(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getStreamKeyAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getStreamSession(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getStreamSessionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result importPlaybackKeyPair(array $args = [])
 * @method \GuzzleHttp\Promise\Promise importPlaybackKeyPairAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listChannels(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listChannelsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listPlaybackKeyPairs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPlaybackKeyPairsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listRecordingConfigurations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listRecordingConfigurationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listStreamKeys(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listStreamKeysAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listStreamSessions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listStreamSessionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listStreams(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listStreamsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putMetadata(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putMetadataAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result startViewerSessionRevocation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startViewerSessionRevocationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result stopStream(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopStreamAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateChannel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateChannelAsync(array $args = [])
 */
class IVSClient extends AwsClient {}
