<?php
namespace CloudBeds\Aws\MskFork\AmplifyBackend;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **AmplifyBackend** service.
 * @method \CloudBeds\Aws\MskFork\Result cloneBackend(array $args = [])
 * @method \GuzzleHttp\Promise\Promise cloneBackendAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createBackend(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createBackendAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createBackendAPI(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createBackendAPIAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createBackendAuth(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createBackendAuthAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createBackendConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createBackendConfigAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createBackendStorage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createBackendStorageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createToken(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createTokenAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteBackend(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteBackendAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteBackendAPI(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteBackendAPIAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteBackendAuth(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteBackendAuthAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteBackendStorage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteBackendStorageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteToken(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteTokenAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result generateBackendAPIModels(array $args = [])
 * @method \GuzzleHttp\Promise\Promise generateBackendAPIModelsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getBackend(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getBackendAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getBackendAPI(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getBackendAPIAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getBackendAPIModels(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getBackendAPIModelsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getBackendAuth(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getBackendAuthAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getBackendJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getBackendJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getBackendStorage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getBackendStorageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getToken(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getTokenAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result importBackendAuth(array $args = [])
 * @method \GuzzleHttp\Promise\Promise importBackendAuthAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result importBackendStorage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise importBackendStorageAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listBackendJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listBackendJobsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listS3Buckets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listS3BucketsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result removeAllBackends(array $args = [])
 * @method \GuzzleHttp\Promise\Promise removeAllBackendsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result removeBackendConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise removeBackendConfigAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateBackendAPI(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateBackendAPIAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateBackendAuth(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateBackendAuthAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateBackendConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateBackendConfigAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateBackendJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateBackendJobAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateBackendStorage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateBackendStorageAsync(array $args = [])
 */
class AmplifyBackendClient extends AwsClient {}
