<?php
namespace CloudBeds\Aws\MskFork\CloudSearch;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **Amazon CloudSearch** service.
 *
 * @method \CloudBeds\Aws\MskFork\Result buildSuggesters(array $args = [])
 * @method \GuzzleHttp\Promise\Promise buildSuggestersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createDomain(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createDomainAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result defineAnalysisScheme(array $args = [])
 * @method \GuzzleHttp\Promise\Promise defineAnalysisSchemeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result defineExpression(array $args = [])
 * @method \GuzzleHttp\Promise\Promise defineExpressionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result defineIndexField(array $args = [])
 * @method \GuzzleHttp\Promise\Promise defineIndexFieldAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result defineSuggester(array $args = [])
 * @method \GuzzleHttp\Promise\Promise defineSuggesterAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAnalysisScheme(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAnalysisSchemeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteDomain(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDomainAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteExpression(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteExpressionAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteIndexField(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteIndexFieldAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteSuggester(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSuggesterAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeAnalysisSchemes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAnalysisSchemesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeAvailabilityOptions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAvailabilityOptionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeDomainEndpointOptions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDomainEndpointOptionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeDomains(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDomainsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeExpressions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeExpressionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeIndexFields(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeIndexFieldsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeScalingParameters(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeScalingParametersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeServiceAccessPolicies(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeServiceAccessPoliciesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeSuggesters(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeSuggestersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result indexDocuments(array $args = [])
 * @method \GuzzleHttp\Promise\Promise indexDocumentsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listDomainNames(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDomainNamesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateAvailabilityOptions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAvailabilityOptionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateDomainEndpointOptions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateDomainEndpointOptionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateScalingParameters(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateScalingParametersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateServiceAccessPolicies(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateServiceAccessPoliciesAsync(array $args = [])
 */
class CloudSearchClient extends AwsClient {}
