<?php
namespace CloudBeds\Aws\MskFork\ChimeSDKIdentity;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **Amazon Chime SDK Identity** service.
 * @method \CloudBeds\Aws\MskFork\Result createAppInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAppInstanceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createAppInstanceAdmin(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAppInstanceAdminAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createAppInstanceBot(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAppInstanceBotAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createAppInstanceUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAppInstanceUserAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAppInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAppInstanceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAppInstanceAdmin(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAppInstanceAdminAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAppInstanceBot(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAppInstanceBotAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAppInstanceUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAppInstanceUserAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deregisterAppInstanceUserEndpoint(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deregisterAppInstanceUserEndpointAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeAppInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAppInstanceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeAppInstanceAdmin(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAppInstanceAdminAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeAppInstanceBot(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAppInstanceBotAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeAppInstanceUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAppInstanceUserAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeAppInstanceUserEndpoint(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAppInstanceUserEndpointAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAppInstanceRetentionSettings(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAppInstanceRetentionSettingsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAppInstanceAdmins(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAppInstanceAdminsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAppInstanceBots(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAppInstanceBotsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAppInstanceUserEndpoints(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAppInstanceUserEndpointsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAppInstanceUsers(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAppInstanceUsersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAppInstances(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAppInstancesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putAppInstanceRetentionSettings(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putAppInstanceRetentionSettingsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result putAppInstanceUserExpirationSettings(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putAppInstanceUserExpirationSettingsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result registerAppInstanceUserEndpoint(array $args = [])
 * @method \GuzzleHttp\Promise\Promise registerAppInstanceUserEndpointAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateAppInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAppInstanceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateAppInstanceBot(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAppInstanceBotAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateAppInstanceUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAppInstanceUserAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateAppInstanceUserEndpoint(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAppInstanceUserEndpointAsync(array $args = [])
 */
class ChimeSDKIdentityClient extends AwsClient {}
