<?php
namespace CloudBeds\Aws\MskFork\ManagedBlockchain;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **Amazon Managed Blockchain** service.
 * @method \CloudBeds\Aws\MskFork\Result createAccessor(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAccessorAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createMember(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createMemberAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createNetwork(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createNetworkAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createNode(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createNodeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createProposal(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createProposalAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteAccessor(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAccessorAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteMember(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteMemberAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteNode(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteNodeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getAccessor(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAccessorAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getMember(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getMemberAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getNetwork(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getNetworkAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getNode(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getNodeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getProposal(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getProposalAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAccessors(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAccessorsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listInvitations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listInvitationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listMembers(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listMembersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listNetworks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listNetworksAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listNodes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listNodesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listProposalVotes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listProposalVotesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listProposals(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listProposalsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result rejectInvitation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise rejectInvitationAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateMember(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateMemberAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateNode(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateNodeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result voteOnProposal(array $args = [])
 * @method \GuzzleHttp\Promise\Promise voteOnProposalAsync(array $args = [])
 */
class ManagedBlockchainClient extends AwsClient {}
