<?php
namespace CloudBeds\Aws\MskFork\MemoryDB;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **Amazon MemoryDB** service.
 * @method \CloudBeds\Aws\MskFork\Result batchUpdateCluster(array $args = [])
 * @method \GuzzleHttp\Promise\Promise batchUpdateClusterAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result copySnapshot(array $args = [])
 * @method \GuzzleHttp\Promise\Promise copySnapshotAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createACL(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createACLAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createCluster(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createClusterAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createParameterGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createParameterGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createSnapshot(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createSnapshotAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createSubnetGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createSubnetGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createUserAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteACL(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteACLAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteCluster(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteClusterAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteParameterGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteParameterGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteSnapshot(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSnapshotAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteSubnetGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSubnetGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteUserAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeACLs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeACLsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeClusters(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeClustersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeEngineVersions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeEngineVersionsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeEvents(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeEventsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeParameterGroups(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeParameterGroupsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeParameters(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeParametersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeReservedNodes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeReservedNodesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeReservedNodesOfferings(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeReservedNodesOfferingsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeServiceUpdates(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeServiceUpdatesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeSnapshots(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeSnapshotsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeSubnetGroups(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeSubnetGroupsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeUsers(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeUsersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result failoverShard(array $args = [])
 * @method \GuzzleHttp\Promise\Promise failoverShardAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listAllowedNodeTypeUpdates(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAllowedNodeTypeUpdatesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result listTags(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result purchaseReservedNodesOffering(array $args = [])
 * @method \GuzzleHttp\Promise\Promise purchaseReservedNodesOfferingAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result resetParameterGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise resetParameterGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateACL(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateACLAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateCluster(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateClusterAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateParameterGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateParameterGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateSubnetGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateSubnetGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result updateUser(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateUserAsync(array $args = [])
 */
class MemoryDBClient extends AwsClient {}
