<?php
namespace CloudBeds\Aws\MskFork\ElasticLoadBalancingV2;

use CloudBeds\Aws\MskFork\AwsClient;

/**
 * This client is used to interact with the **Elastic Load Balancing** service.
 * @method \CloudBeds\Aws\MskFork\Result addListenerCertificates(array $args = [])
 * @method \GuzzleHttp\Promise\Promise addListenerCertificatesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result addTags(array $args = [])
 * @method \GuzzleHttp\Promise\Promise addTagsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result addTrustStoreRevocations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise addTrustStoreRevocationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createListener(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createListenerAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createLoadBalancer(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createLoadBalancerAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createRule(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createRuleAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createTargetGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createTargetGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result createTrustStore(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createTrustStoreAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteListener(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteListenerAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteLoadBalancer(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteLoadBalancerAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteRule(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteRuleAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteTargetGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteTargetGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deleteTrustStore(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteTrustStoreAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result deregisterTargets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deregisterTargetsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeAccountLimits(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAccountLimitsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeListenerCertificates(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeListenerCertificatesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeListeners(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeListenersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeLoadBalancerAttributes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeLoadBalancerAttributesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeLoadBalancers(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeLoadBalancersAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeRules(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeRulesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeSSLPolicies(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeSSLPoliciesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeTags(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeTagsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeTargetGroupAttributes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeTargetGroupAttributesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeTargetGroups(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeTargetGroupsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeTargetHealth(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeTargetHealthAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeTrustStoreAssociations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeTrustStoreAssociationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeTrustStoreRevocations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeTrustStoreRevocationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result describeTrustStores(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeTrustStoresAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getTrustStoreCaCertificatesBundle(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getTrustStoreCaCertificatesBundleAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result getTrustStoreRevocationContent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getTrustStoreRevocationContentAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result modifyListener(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyListenerAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result modifyLoadBalancerAttributes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyLoadBalancerAttributesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result modifyRule(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyRuleAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result modifyTargetGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyTargetGroupAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result modifyTargetGroupAttributes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyTargetGroupAttributesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result modifyTrustStore(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyTrustStoreAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result registerTargets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise registerTargetsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result removeListenerCertificates(array $args = [])
 * @method \GuzzleHttp\Promise\Promise removeListenerCertificatesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result removeTags(array $args = [])
 * @method \GuzzleHttp\Promise\Promise removeTagsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result removeTrustStoreRevocations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise removeTrustStoreRevocationsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result setIpAddressType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise setIpAddressTypeAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result setRulePriorities(array $args = [])
 * @method \GuzzleHttp\Promise\Promise setRulePrioritiesAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result setSecurityGroups(array $args = [])
 * @method \GuzzleHttp\Promise\Promise setSecurityGroupsAsync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Result setSubnets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise setSubnetsAsync(array $args = [])
 */
class ElasticLoadBalancingV2Client extends AwsClient {}
