<?php
namespace CloudBeds\Aws\MskFork;

/**
 * Builds AWS clients based on configuration settings.
 *
 * @method \CloudBeds\Aws\MskFork\ACMPCA\ACMPCAClient createACMPCA(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionACMPCA(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ARCZonalShift\ARCZonalShiftClient createARCZonalShift(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionARCZonalShift(array $args = [])
 * @method \CloudBeds\Aws\MskFork\AccessAnalyzer\AccessAnalyzerClient createAccessAnalyzer(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAccessAnalyzer(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Account\AccountClient createAccount(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAccount(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Acm\AcmClient createAcm(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAcm(array $args = [])
 * @method \CloudBeds\Aws\MskFork\AlexaForBusiness\AlexaForBusinessClient createAlexaForBusiness(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAlexaForBusiness(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Amplify\AmplifyClient createAmplify(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAmplify(array $args = [])
 * @method \CloudBeds\Aws\MskFork\AmplifyBackend\AmplifyBackendClient createAmplifyBackend(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAmplifyBackend(array $args = [])
 * @method \CloudBeds\Aws\MskFork\AmplifyUIBuilder\AmplifyUIBuilderClient createAmplifyUIBuilder(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAmplifyUIBuilder(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ApiGateway\ApiGatewayClient createApiGateway(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionApiGateway(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ApiGatewayManagementApi\ApiGatewayManagementApiClient createApiGatewayManagementApi(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionApiGatewayManagementApi(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ApiGatewayV2\ApiGatewayV2Client createApiGatewayV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionApiGatewayV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\AppConfig\AppConfigClient createAppConfig(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAppConfig(array $args = [])
 * @method \CloudBeds\Aws\MskFork\AppConfigData\AppConfigDataClient createAppConfigData(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAppConfigData(array $args = [])
 * @method \CloudBeds\Aws\MskFork\AppFabric\AppFabricClient createAppFabric(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAppFabric(array $args = [])
 * @method \CloudBeds\Aws\MskFork\AppIntegrationsService\AppIntegrationsServiceClient createAppIntegrationsService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAppIntegrationsService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\AppMesh\AppMeshClient createAppMesh(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAppMesh(array $args = [])
 * @method \CloudBeds\Aws\MskFork\AppRegistry\AppRegistryClient createAppRegistry(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAppRegistry(array $args = [])
 * @method \CloudBeds\Aws\MskFork\AppRunner\AppRunnerClient createAppRunner(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAppRunner(array $args = [])
 * @method \CloudBeds\Aws\MskFork\AppSync\AppSyncClient createAppSync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAppSync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Appflow\AppflowClient createAppflow(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAppflow(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ApplicationAutoScaling\ApplicationAutoScalingClient createApplicationAutoScaling(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionApplicationAutoScaling(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ApplicationCostProfiler\ApplicationCostProfilerClient createApplicationCostProfiler(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionApplicationCostProfiler(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ApplicationDiscoveryService\ApplicationDiscoveryServiceClient createApplicationDiscoveryService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionApplicationDiscoveryService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ApplicationInsights\ApplicationInsightsClient createApplicationInsights(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionApplicationInsights(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Appstream\AppstreamClient createAppstream(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAppstream(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Athena\AthenaClient createAthena(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAthena(array $args = [])
 * @method \CloudBeds\Aws\MskFork\AuditManager\AuditManagerClient createAuditManager(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAuditManager(array $args = [])
 * @method \CloudBeds\Aws\MskFork\AugmentedAIRuntime\AugmentedAIRuntimeClient createAugmentedAIRuntime(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAugmentedAIRuntime(array $args = [])
 * @method \CloudBeds\Aws\MskFork\AutoScaling\AutoScalingClient createAutoScaling(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAutoScaling(array $args = [])
 * @method \CloudBeds\Aws\MskFork\AutoScalingPlans\AutoScalingPlansClient createAutoScalingPlans(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionAutoScalingPlans(array $args = [])
 * @method \CloudBeds\Aws\MskFork\B2bi\B2biClient createB2bi(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionB2bi(array $args = [])
 * @method \CloudBeds\Aws\MskFork\BCMDataExports\BCMDataExportsClient createBCMDataExports(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionBCMDataExports(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Backup\BackupClient createBackup(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionBackup(array $args = [])
 * @method \CloudBeds\Aws\MskFork\BackupGateway\BackupGatewayClient createBackupGateway(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionBackupGateway(array $args = [])
 * @method \CloudBeds\Aws\MskFork\BackupStorage\BackupStorageClient createBackupStorage(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionBackupStorage(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Batch\BatchClient createBatch(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionBatch(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Bedrock\BedrockClient createBedrock(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionBedrock(array $args = [])
 * @method \CloudBeds\Aws\MskFork\BedrockAgent\BedrockAgentClient createBedrockAgent(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionBedrockAgent(array $args = [])
 * @method \CloudBeds\Aws\MskFork\BedrockAgentRuntime\BedrockAgentRuntimeClient createBedrockAgentRuntime(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionBedrockAgentRuntime(array $args = [])
 * @method \CloudBeds\Aws\MskFork\BedrockRuntime\BedrockRuntimeClient createBedrockRuntime(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionBedrockRuntime(array $args = [])
 * @method \CloudBeds\Aws\MskFork\BillingConductor\BillingConductorClient createBillingConductor(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionBillingConductor(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Braket\BraketClient createBraket(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionBraket(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Budgets\BudgetsClient createBudgets(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionBudgets(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Chime\ChimeClient createChime(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionChime(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ChimeSDKIdentity\ChimeSDKIdentityClient createChimeSDKIdentity(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionChimeSDKIdentity(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ChimeSDKMediaPipelines\ChimeSDKMediaPipelinesClient createChimeSDKMediaPipelines(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionChimeSDKMediaPipelines(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ChimeSDKMeetings\ChimeSDKMeetingsClient createChimeSDKMeetings(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionChimeSDKMeetings(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ChimeSDKMessaging\ChimeSDKMessagingClient createChimeSDKMessaging(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionChimeSDKMessaging(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ChimeSDKVoice\ChimeSDKVoiceClient createChimeSDKVoice(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionChimeSDKVoice(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CleanRooms\CleanRoomsClient createCleanRooms(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCleanRooms(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CleanRoomsML\CleanRoomsMLClient createCleanRoomsML(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCleanRoomsML(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Cloud9\Cloud9Client createCloud9(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCloud9(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CloudControlApi\CloudControlApiClient createCloudControlApi(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCloudControlApi(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CloudDirectory\CloudDirectoryClient createCloudDirectory(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCloudDirectory(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CloudFormation\CloudFormationClient createCloudFormation(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCloudFormation(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CloudFront\CloudFrontClient createCloudFront(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCloudFront(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CloudFrontKeyValueStore\CloudFrontKeyValueStoreClient createCloudFrontKeyValueStore(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCloudFrontKeyValueStore(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CloudHSMV2\CloudHSMV2Client createCloudHSMV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCloudHSMV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CloudHsm\CloudHsmClient createCloudHsm(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCloudHsm(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CloudSearch\CloudSearchClient createCloudSearch(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCloudSearch(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CloudSearchDomain\CloudSearchDomainClient createCloudSearchDomain(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCloudSearchDomain(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CloudTrail\CloudTrailClient createCloudTrail(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCloudTrail(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CloudTrailData\CloudTrailDataClient createCloudTrailData(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCloudTrailData(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CloudWatch\CloudWatchClient createCloudWatch(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCloudWatch(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CloudWatchEvents\CloudWatchEventsClient createCloudWatchEvents(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCloudWatchEvents(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CloudWatchEvidently\CloudWatchEvidentlyClient createCloudWatchEvidently(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCloudWatchEvidently(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CloudWatchLogs\CloudWatchLogsClient createCloudWatchLogs(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCloudWatchLogs(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CloudWatchRUM\CloudWatchRUMClient createCloudWatchRUM(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCloudWatchRUM(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CodeArtifact\CodeArtifactClient createCodeArtifact(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCodeArtifact(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CodeBuild\CodeBuildClient createCodeBuild(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCodeBuild(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CodeCatalyst\CodeCatalystClient createCodeCatalyst(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCodeCatalyst(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CodeCommit\CodeCommitClient createCodeCommit(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCodeCommit(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CodeDeploy\CodeDeployClient createCodeDeploy(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCodeDeploy(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CodeGuruProfiler\CodeGuruProfilerClient createCodeGuruProfiler(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCodeGuruProfiler(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CodeGuruReviewer\CodeGuruReviewerClient createCodeGuruReviewer(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCodeGuruReviewer(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CodeGuruSecurity\CodeGuruSecurityClient createCodeGuruSecurity(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCodeGuruSecurity(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CodePipeline\CodePipelineClient createCodePipeline(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCodePipeline(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CodeStar\CodeStarClient createCodeStar(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCodeStar(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CodeStarNotifications\CodeStarNotificationsClient createCodeStarNotifications(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCodeStarNotifications(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CodeStarconnections\CodeStarconnectionsClient createCodeStarconnections(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCodeStarconnections(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CognitoIdentity\CognitoIdentityClient createCognitoIdentity(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCognitoIdentity(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CognitoIdentityProvider\CognitoIdentityProviderClient createCognitoIdentityProvider(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCognitoIdentityProvider(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CognitoSync\CognitoSyncClient createCognitoSync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCognitoSync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Comprehend\ComprehendClient createComprehend(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionComprehend(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ComprehendMedical\ComprehendMedicalClient createComprehendMedical(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionComprehendMedical(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ComputeOptimizer\ComputeOptimizerClient createComputeOptimizer(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionComputeOptimizer(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ConfigService\ConfigServiceClient createConfigService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionConfigService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Connect\ConnectClient createConnect(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionConnect(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ConnectCampaignService\ConnectCampaignServiceClient createConnectCampaignService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionConnectCampaignService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ConnectCases\ConnectCasesClient createConnectCases(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionConnectCases(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ConnectContactLens\ConnectContactLensClient createConnectContactLens(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionConnectContactLens(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ConnectParticipant\ConnectParticipantClient createConnectParticipant(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionConnectParticipant(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ConnectWisdomService\ConnectWisdomServiceClient createConnectWisdomService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionConnectWisdomService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ControlTower\ControlTowerClient createControlTower(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionControlTower(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CostExplorer\CostExplorerClient createCostExplorer(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCostExplorer(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CostOptimizationHub\CostOptimizationHubClient createCostOptimizationHub(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCostOptimizationHub(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CostandUsageReportService\CostandUsageReportServiceClient createCostandUsageReportService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCostandUsageReportService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\CustomerProfiles\CustomerProfilesClient createCustomerProfiles(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionCustomerProfiles(array $args = [])
 * @method \CloudBeds\Aws\MskFork\DAX\DAXClient createDAX(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionDAX(array $args = [])
 * @method \CloudBeds\Aws\MskFork\DLM\DLMClient createDLM(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionDLM(array $args = [])
 * @method \CloudBeds\Aws\MskFork\DataExchange\DataExchangeClient createDataExchange(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionDataExchange(array $args = [])
 * @method \CloudBeds\Aws\MskFork\DataPipeline\DataPipelineClient createDataPipeline(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionDataPipeline(array $args = [])
 * @method \CloudBeds\Aws\MskFork\DataSync\DataSyncClient createDataSync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionDataSync(array $args = [])
 * @method \CloudBeds\Aws\MskFork\DataZone\DataZoneClient createDataZone(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionDataZone(array $args = [])
 * @method \CloudBeds\Aws\MskFork\DatabaseMigrationService\DatabaseMigrationServiceClient createDatabaseMigrationService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionDatabaseMigrationService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Detective\DetectiveClient createDetective(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionDetective(array $args = [])
 * @method \CloudBeds\Aws\MskFork\DevOpsGuru\DevOpsGuruClient createDevOpsGuru(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionDevOpsGuru(array $args = [])
 * @method \CloudBeds\Aws\MskFork\DeviceFarm\DeviceFarmClient createDeviceFarm(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionDeviceFarm(array $args = [])
 * @method \CloudBeds\Aws\MskFork\DirectConnect\DirectConnectClient createDirectConnect(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionDirectConnect(array $args = [])
 * @method \CloudBeds\Aws\MskFork\DirectoryService\DirectoryServiceClient createDirectoryService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionDirectoryService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\DocDB\DocDBClient createDocDB(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionDocDB(array $args = [])
 * @method \CloudBeds\Aws\MskFork\DocDBElastic\DocDBElasticClient createDocDBElastic(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionDocDBElastic(array $args = [])
 * @method \CloudBeds\Aws\MskFork\DynamoDb\DynamoDbClient createDynamoDb(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionDynamoDb(array $args = [])
 * @method \CloudBeds\Aws\MskFork\DynamoDbStreams\DynamoDbStreamsClient createDynamoDbStreams(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionDynamoDbStreams(array $args = [])
 * @method \CloudBeds\Aws\MskFork\EBS\EBSClient createEBS(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionEBS(array $args = [])
 * @method \CloudBeds\Aws\MskFork\EC2InstanceConnect\EC2InstanceConnectClient createEC2InstanceConnect(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionEC2InstanceConnect(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ECRPublic\ECRPublicClient createECRPublic(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionECRPublic(array $args = [])
 * @method \CloudBeds\Aws\MskFork\EKS\EKSClient createEKS(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionEKS(array $args = [])
 * @method \CloudBeds\Aws\MskFork\EKSAuth\EKSAuthClient createEKSAuth(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionEKSAuth(array $args = [])
 * @method \CloudBeds\Aws\MskFork\EMRContainers\EMRContainersClient createEMRContainers(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionEMRContainers(array $args = [])
 * @method \CloudBeds\Aws\MskFork\EMRServerless\EMRServerlessClient createEMRServerless(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionEMRServerless(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Ec2\Ec2Client createEc2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionEc2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Ecr\EcrClient createEcr(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionEcr(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Ecs\EcsClient createEcs(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionEcs(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Efs\EfsClient createEfs(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionEfs(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ElastiCache\ElastiCacheClient createElastiCache(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionElastiCache(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ElasticBeanstalk\ElasticBeanstalkClient createElasticBeanstalk(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionElasticBeanstalk(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ElasticInference\ElasticInferenceClient createElasticInference(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionElasticInference(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ElasticLoadBalancing\ElasticLoadBalancingClient createElasticLoadBalancing(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionElasticLoadBalancing(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ElasticLoadBalancingV2\ElasticLoadBalancingV2Client createElasticLoadBalancingV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionElasticLoadBalancingV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ElasticTranscoder\ElasticTranscoderClient createElasticTranscoder(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionElasticTranscoder(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ElasticsearchService\ElasticsearchServiceClient createElasticsearchService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionElasticsearchService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Emr\EmrClient createEmr(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionEmr(array $args = [])
 * @method \CloudBeds\Aws\MskFork\EntityResolution\EntityResolutionClient createEntityResolution(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionEntityResolution(array $args = [])
 * @method \CloudBeds\Aws\MskFork\EventBridge\EventBridgeClient createEventBridge(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionEventBridge(array $args = [])
 * @method \CloudBeds\Aws\MskFork\FIS\FISClient createFIS(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionFIS(array $args = [])
 * @method \CloudBeds\Aws\MskFork\FMS\FMSClient createFMS(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionFMS(array $args = [])
 * @method \CloudBeds\Aws\MskFork\FSx\FSxClient createFSx(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionFSx(array $args = [])
 * @method \CloudBeds\Aws\MskFork\FinSpaceData\FinSpaceDataClient createFinSpaceData(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionFinSpaceData(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Firehose\FirehoseClient createFirehose(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionFirehose(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ForecastQueryService\ForecastQueryServiceClient createForecastQueryService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionForecastQueryService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ForecastService\ForecastServiceClient createForecastService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionForecastService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\FraudDetector\FraudDetectorClient createFraudDetector(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionFraudDetector(array $args = [])
 * @method \CloudBeds\Aws\MskFork\FreeTier\FreeTierClient createFreeTier(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionFreeTier(array $args = [])
 * @method \CloudBeds\Aws\MskFork\GameLift\GameLiftClient createGameLift(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionGameLift(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Glacier\GlacierClient createGlacier(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionGlacier(array $args = [])
 * @method \CloudBeds\Aws\MskFork\GlobalAccelerator\GlobalAcceleratorClient createGlobalAccelerator(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionGlobalAccelerator(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Glue\GlueClient createGlue(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionGlue(array $args = [])
 * @method \CloudBeds\Aws\MskFork\GlueDataBrew\GlueDataBrewClient createGlueDataBrew(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionGlueDataBrew(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Greengrass\GreengrassClient createGreengrass(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionGreengrass(array $args = [])
 * @method \CloudBeds\Aws\MskFork\GreengrassV2\GreengrassV2Client createGreengrassV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionGreengrassV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\GroundStation\GroundStationClient createGroundStation(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionGroundStation(array $args = [])
 * @method \CloudBeds\Aws\MskFork\GuardDuty\GuardDutyClient createGuardDuty(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionGuardDuty(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Health\HealthClient createHealth(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionHealth(array $args = [])
 * @method \CloudBeds\Aws\MskFork\HealthLake\HealthLakeClient createHealthLake(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionHealthLake(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Honeycode\HoneycodeClient createHoneycode(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionHoneycode(array $args = [])
 * @method \CloudBeds\Aws\MskFork\IVS\IVSClient createIVS(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIVS(array $args = [])
 * @method \CloudBeds\Aws\MskFork\IVSRealTime\IVSRealTimeClient createIVSRealTime(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIVSRealTime(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Iam\IamClient createIam(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIam(array $args = [])
 * @method \CloudBeds\Aws\MskFork\IdentityStore\IdentityStoreClient createIdentityStore(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIdentityStore(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ImportExport\ImportExportClient createImportExport(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionImportExport(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Inspector\InspectorClient createInspector(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionInspector(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Inspector2\Inspector2Client createInspector2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionInspector2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\InspectorScan\InspectorScanClient createInspectorScan(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionInspectorScan(array $args = [])
 * @method \CloudBeds\Aws\MskFork\InternetMonitor\InternetMonitorClient createInternetMonitor(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionInternetMonitor(array $args = [])
 * @method \CloudBeds\Aws\MskFork\IoT1ClickDevicesService\IoT1ClickDevicesServiceClient createIoT1ClickDevicesService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIoT1ClickDevicesService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\IoT1ClickProjects\IoT1ClickProjectsClient createIoT1ClickProjects(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIoT1ClickProjects(array $args = [])
 * @method \CloudBeds\Aws\MskFork\IoTAnalytics\IoTAnalyticsClient createIoTAnalytics(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIoTAnalytics(array $args = [])
 * @method \CloudBeds\Aws\MskFork\IoTDeviceAdvisor\IoTDeviceAdvisorClient createIoTDeviceAdvisor(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIoTDeviceAdvisor(array $args = [])
 * @method \CloudBeds\Aws\MskFork\IoTEvents\IoTEventsClient createIoTEvents(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIoTEvents(array $args = [])
 * @method \CloudBeds\Aws\MskFork\IoTEventsData\IoTEventsDataClient createIoTEventsData(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIoTEventsData(array $args = [])
 * @method \CloudBeds\Aws\MskFork\IoTFleetHub\IoTFleetHubClient createIoTFleetHub(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIoTFleetHub(array $args = [])
 * @method \CloudBeds\Aws\MskFork\IoTFleetWise\IoTFleetWiseClient createIoTFleetWise(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIoTFleetWise(array $args = [])
 * @method \CloudBeds\Aws\MskFork\IoTJobsDataPlane\IoTJobsDataPlaneClient createIoTJobsDataPlane(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIoTJobsDataPlane(array $args = [])
 * @method \CloudBeds\Aws\MskFork\IoTRoboRunner\IoTRoboRunnerClient createIoTRoboRunner(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIoTRoboRunner(array $args = [])
 * @method \CloudBeds\Aws\MskFork\IoTSecureTunneling\IoTSecureTunnelingClient createIoTSecureTunneling(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIoTSecureTunneling(array $args = [])
 * @method \CloudBeds\Aws\MskFork\IoTSiteWise\IoTSiteWiseClient createIoTSiteWise(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIoTSiteWise(array $args = [])
 * @method \CloudBeds\Aws\MskFork\IoTThingsGraph\IoTThingsGraphClient createIoTThingsGraph(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIoTThingsGraph(array $args = [])
 * @method \CloudBeds\Aws\MskFork\IoTTwinMaker\IoTTwinMakerClient createIoTTwinMaker(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIoTTwinMaker(array $args = [])
 * @method \CloudBeds\Aws\MskFork\IoTWireless\IoTWirelessClient createIoTWireless(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIoTWireless(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Iot\IotClient createIot(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIot(array $args = [])
 * @method \CloudBeds\Aws\MskFork\IotDataPlane\IotDataPlaneClient createIotDataPlane(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionIotDataPlane(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Kafka\KafkaClient createKafka(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionKafka(array $args = [])
 * @method \CloudBeds\Aws\MskFork\KafkaConnect\KafkaConnectClient createKafkaConnect(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionKafkaConnect(array $args = [])
 * @method \CloudBeds\Aws\MskFork\KendraRanking\KendraRankingClient createKendraRanking(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionKendraRanking(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Keyspaces\KeyspacesClient createKeyspaces(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionKeyspaces(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Kinesis\KinesisClient createKinesis(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionKinesis(array $args = [])
 * @method \CloudBeds\Aws\MskFork\KinesisAnalytics\KinesisAnalyticsClient createKinesisAnalytics(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionKinesisAnalytics(array $args = [])
 * @method \CloudBeds\Aws\MskFork\KinesisAnalyticsV2\KinesisAnalyticsV2Client createKinesisAnalyticsV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionKinesisAnalyticsV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\KinesisVideo\KinesisVideoClient createKinesisVideo(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionKinesisVideo(array $args = [])
 * @method \CloudBeds\Aws\MskFork\KinesisVideoArchivedMedia\KinesisVideoArchivedMediaClient createKinesisVideoArchivedMedia(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionKinesisVideoArchivedMedia(array $args = [])
 * @method \CloudBeds\Aws\MskFork\KinesisVideoMedia\KinesisVideoMediaClient createKinesisVideoMedia(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionKinesisVideoMedia(array $args = [])
 * @method \CloudBeds\Aws\MskFork\KinesisVideoSignalingChannels\KinesisVideoSignalingChannelsClient createKinesisVideoSignalingChannels(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionKinesisVideoSignalingChannels(array $args = [])
 * @method \CloudBeds\Aws\MskFork\KinesisVideoWebRTCStorage\KinesisVideoWebRTCStorageClient createKinesisVideoWebRTCStorage(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionKinesisVideoWebRTCStorage(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Kms\KmsClient createKms(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionKms(array $args = [])
 * @method \CloudBeds\Aws\MskFork\LakeFormation\LakeFormationClient createLakeFormation(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionLakeFormation(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Lambda\LambdaClient createLambda(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionLambda(array $args = [])
 * @method \CloudBeds\Aws\MskFork\LaunchWizard\LaunchWizardClient createLaunchWizard(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionLaunchWizard(array $args = [])
 * @method \CloudBeds\Aws\MskFork\LexModelBuildingService\LexModelBuildingServiceClient createLexModelBuildingService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionLexModelBuildingService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\LexModelsV2\LexModelsV2Client createLexModelsV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionLexModelsV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\LexRuntimeService\LexRuntimeServiceClient createLexRuntimeService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionLexRuntimeService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\LexRuntimeV2\LexRuntimeV2Client createLexRuntimeV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionLexRuntimeV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\LicenseManager\LicenseManagerClient createLicenseManager(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionLicenseManager(array $args = [])
 * @method \CloudBeds\Aws\MskFork\LicenseManagerLinuxSubscriptions\LicenseManagerLinuxSubscriptionsClient createLicenseManagerLinuxSubscriptions(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionLicenseManagerLinuxSubscriptions(array $args = [])
 * @method \CloudBeds\Aws\MskFork\LicenseManagerUserSubscriptions\LicenseManagerUserSubscriptionsClient createLicenseManagerUserSubscriptions(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionLicenseManagerUserSubscriptions(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Lightsail\LightsailClient createLightsail(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionLightsail(array $args = [])
 * @method \CloudBeds\Aws\MskFork\LocationService\LocationServiceClient createLocationService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionLocationService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\LookoutEquipment\LookoutEquipmentClient createLookoutEquipment(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionLookoutEquipment(array $args = [])
 * @method \CloudBeds\Aws\MskFork\LookoutMetrics\LookoutMetricsClient createLookoutMetrics(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionLookoutMetrics(array $args = [])
 * @method \CloudBeds\Aws\MskFork\LookoutforVision\LookoutforVisionClient createLookoutforVision(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionLookoutforVision(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MQ\MQClient createMQ(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMQ(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MTurk\MTurkClient createMTurk(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMTurk(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MWAA\MWAAClient createMWAA(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMWAA(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MachineLearning\MachineLearningClient createMachineLearning(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMachineLearning(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Macie2\Macie2Client createMacie2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMacie2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MainframeModernization\MainframeModernizationClient createMainframeModernization(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMainframeModernization(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ManagedBlockchain\ManagedBlockchainClient createManagedBlockchain(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionManagedBlockchain(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ManagedBlockchainQuery\ManagedBlockchainQueryClient createManagedBlockchainQuery(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionManagedBlockchainQuery(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ManagedGrafana\ManagedGrafanaClient createManagedGrafana(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionManagedGrafana(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MarketplaceAgreement\MarketplaceAgreementClient createMarketplaceAgreement(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMarketplaceAgreement(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MarketplaceCatalog\MarketplaceCatalogClient createMarketplaceCatalog(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMarketplaceCatalog(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MarketplaceCommerceAnalytics\MarketplaceCommerceAnalyticsClient createMarketplaceCommerceAnalytics(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMarketplaceCommerceAnalytics(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MarketplaceDeployment\MarketplaceDeploymentClient createMarketplaceDeployment(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMarketplaceDeployment(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MarketplaceEntitlementService\MarketplaceEntitlementServiceClient createMarketplaceEntitlementService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMarketplaceEntitlementService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MarketplaceMetering\MarketplaceMeteringClient createMarketplaceMetering(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMarketplaceMetering(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MediaConnect\MediaConnectClient createMediaConnect(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMediaConnect(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MediaConvert\MediaConvertClient createMediaConvert(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMediaConvert(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MediaLive\MediaLiveClient createMediaLive(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMediaLive(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MediaPackage\MediaPackageClient createMediaPackage(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMediaPackage(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MediaPackageV2\MediaPackageV2Client createMediaPackageV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMediaPackageV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MediaPackageVod\MediaPackageVodClient createMediaPackageVod(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMediaPackageVod(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MediaStore\MediaStoreClient createMediaStore(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMediaStore(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MediaStoreData\MediaStoreDataClient createMediaStoreData(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMediaStoreData(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MediaTailor\MediaTailorClient createMediaTailor(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMediaTailor(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MedicalImaging\MedicalImagingClient createMedicalImaging(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMedicalImaging(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MemoryDB\MemoryDBClient createMemoryDB(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMemoryDB(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MigrationHub\MigrationHubClient createMigrationHub(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMigrationHub(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MigrationHubConfig\MigrationHubConfigClient createMigrationHubConfig(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMigrationHubConfig(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MigrationHubOrchestrator\MigrationHubOrchestratorClient createMigrationHubOrchestrator(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMigrationHubOrchestrator(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MigrationHubRefactorSpaces\MigrationHubRefactorSpacesClient createMigrationHubRefactorSpaces(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMigrationHubRefactorSpaces(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MigrationHubStrategyRecommendations\MigrationHubStrategyRecommendationsClient createMigrationHubStrategyRecommendations(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMigrationHubStrategyRecommendations(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Mobile\MobileClient createMobile(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionMobile(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Neptune\NeptuneClient createNeptune(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionNeptune(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Neptunedata\NeptunedataClient createNeptunedata(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionNeptunedata(array $args = [])
 * @method \CloudBeds\Aws\MskFork\NetworkFirewall\NetworkFirewallClient createNetworkFirewall(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionNetworkFirewall(array $args = [])
 * @method \CloudBeds\Aws\MskFork\NetworkManager\NetworkManagerClient createNetworkManager(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionNetworkManager(array $args = [])
 * @method \CloudBeds\Aws\MskFork\NimbleStudio\NimbleStudioClient createNimbleStudio(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionNimbleStudio(array $args = [])
 * @method \CloudBeds\Aws\MskFork\OAM\OAMClient createOAM(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionOAM(array $args = [])
 * @method \CloudBeds\Aws\MskFork\OSIS\OSISClient createOSIS(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionOSIS(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Omics\OmicsClient createOmics(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionOmics(array $args = [])
 * @method \CloudBeds\Aws\MskFork\OpenSearchServerless\OpenSearchServerlessClient createOpenSearchServerless(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionOpenSearchServerless(array $args = [])
 * @method \CloudBeds\Aws\MskFork\OpenSearchService\OpenSearchServiceClient createOpenSearchService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionOpenSearchService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\OpsWorks\OpsWorksClient createOpsWorks(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionOpsWorks(array $args = [])
 * @method \CloudBeds\Aws\MskFork\OpsWorksCM\OpsWorksCMClient createOpsWorksCM(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionOpsWorksCM(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Organizations\OrganizationsClient createOrganizations(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionOrganizations(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Outposts\OutpostsClient createOutposts(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionOutposts(array $args = [])
 * @method \CloudBeds\Aws\MskFork\PI\PIClient createPI(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionPI(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Panorama\PanoramaClient createPanorama(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionPanorama(array $args = [])
 * @method \CloudBeds\Aws\MskFork\PaymentCryptography\PaymentCryptographyClient createPaymentCryptography(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionPaymentCryptography(array $args = [])
 * @method \CloudBeds\Aws\MskFork\PaymentCryptographyData\PaymentCryptographyDataClient createPaymentCryptographyData(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionPaymentCryptographyData(array $args = [])
 * @method \CloudBeds\Aws\MskFork\PcaConnectorAd\PcaConnectorAdClient createPcaConnectorAd(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionPcaConnectorAd(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Personalize\PersonalizeClient createPersonalize(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionPersonalize(array $args = [])
 * @method \CloudBeds\Aws\MskFork\PersonalizeEvents\PersonalizeEventsClient createPersonalizeEvents(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionPersonalizeEvents(array $args = [])
 * @method \CloudBeds\Aws\MskFork\PersonalizeRuntime\PersonalizeRuntimeClient createPersonalizeRuntime(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionPersonalizeRuntime(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Pinpoint\PinpointClient createPinpoint(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionPinpoint(array $args = [])
 * @method \CloudBeds\Aws\MskFork\PinpointEmail\PinpointEmailClient createPinpointEmail(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionPinpointEmail(array $args = [])
 * @method \CloudBeds\Aws\MskFork\PinpointSMSVoice\PinpointSMSVoiceClient createPinpointSMSVoice(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionPinpointSMSVoice(array $args = [])
 * @method \CloudBeds\Aws\MskFork\PinpointSMSVoiceV2\PinpointSMSVoiceV2Client createPinpointSMSVoiceV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionPinpointSMSVoiceV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Pipes\PipesClient createPipes(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionPipes(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Polly\PollyClient createPolly(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionPolly(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Pricing\PricingClient createPricing(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionPricing(array $args = [])
 * @method \CloudBeds\Aws\MskFork\PrivateNetworks\PrivateNetworksClient createPrivateNetworks(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionPrivateNetworks(array $args = [])
 * @method \CloudBeds\Aws\MskFork\PrometheusService\PrometheusServiceClient createPrometheusService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionPrometheusService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Proton\ProtonClient createProton(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionProton(array $args = [])
 * @method \CloudBeds\Aws\MskFork\QBusiness\QBusinessClient createQBusiness(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionQBusiness(array $args = [])
 * @method \CloudBeds\Aws\MskFork\QConnect\QConnectClient createQConnect(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionQConnect(array $args = [])
 * @method \CloudBeds\Aws\MskFork\QLDB\QLDBClient createQLDB(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionQLDB(array $args = [])
 * @method \CloudBeds\Aws\MskFork\QLDBSession\QLDBSessionClient createQLDBSession(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionQLDBSession(array $args = [])
 * @method \CloudBeds\Aws\MskFork\QuickSight\QuickSightClient createQuickSight(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionQuickSight(array $args = [])
 * @method \CloudBeds\Aws\MskFork\RAM\RAMClient createRAM(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionRAM(array $args = [])
 * @method \CloudBeds\Aws\MskFork\RDSDataService\RDSDataServiceClient createRDSDataService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionRDSDataService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Rds\RdsClient createRds(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionRds(array $args = [])
 * @method \CloudBeds\Aws\MskFork\RecycleBin\RecycleBinClient createRecycleBin(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionRecycleBin(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Redshift\RedshiftClient createRedshift(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionRedshift(array $args = [])
 * @method \CloudBeds\Aws\MskFork\RedshiftDataAPIService\RedshiftDataAPIServiceClient createRedshiftDataAPIService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionRedshiftDataAPIService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\RedshiftServerless\RedshiftServerlessClient createRedshiftServerless(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionRedshiftServerless(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Rekognition\RekognitionClient createRekognition(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionRekognition(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Repostspace\RepostspaceClient createRepostspace(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionRepostspace(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ResilienceHub\ResilienceHubClient createResilienceHub(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionResilienceHub(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ResourceExplorer2\ResourceExplorer2Client createResourceExplorer2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionResourceExplorer2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ResourceGroups\ResourceGroupsClient createResourceGroups(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionResourceGroups(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ResourceGroupsTaggingAPI\ResourceGroupsTaggingAPIClient createResourceGroupsTaggingAPI(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionResourceGroupsTaggingAPI(array $args = [])
 * @method \CloudBeds\Aws\MskFork\RoboMaker\RoboMakerClient createRoboMaker(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionRoboMaker(array $args = [])
 * @method \CloudBeds\Aws\MskFork\RolesAnywhere\RolesAnywhereClient createRolesAnywhere(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionRolesAnywhere(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Route53\Route53Client createRoute53(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionRoute53(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Route53Domains\Route53DomainsClient createRoute53Domains(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionRoute53Domains(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Route53RecoveryCluster\Route53RecoveryClusterClient createRoute53RecoveryCluster(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionRoute53RecoveryCluster(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Route53RecoveryControlConfig\Route53RecoveryControlConfigClient createRoute53RecoveryControlConfig(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionRoute53RecoveryControlConfig(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Route53RecoveryReadiness\Route53RecoveryReadinessClient createRoute53RecoveryReadiness(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionRoute53RecoveryReadiness(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Route53Resolver\Route53ResolverClient createRoute53Resolver(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionRoute53Resolver(array $args = [])
 * @method \CloudBeds\Aws\MskFork\S3\S3Client createS3(array $args = [])
 * @method \CloudBeds\Aws\MskFork\S3\S3MultiRegionClient createMultiRegionS3(array $args = [])
 * @method \CloudBeds\Aws\MskFork\S3Control\S3ControlClient createS3Control(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionS3Control(array $args = [])
 * @method \CloudBeds\Aws\MskFork\S3Outposts\S3OutpostsClient createS3Outposts(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionS3Outposts(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SSMContacts\SSMContactsClient createSSMContacts(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSSMContacts(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SSMIncidents\SSMIncidentsClient createSSMIncidents(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSSMIncidents(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SSO\SSOClient createSSO(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSSO(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SSOAdmin\SSOAdminClient createSSOAdmin(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSSOAdmin(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SSOOIDC\SSOOIDCClient createSSOOIDC(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSSOOIDC(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SageMaker\SageMakerClient createSageMaker(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSageMaker(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SageMakerFeatureStoreRuntime\SageMakerFeatureStoreRuntimeClient createSageMakerFeatureStoreRuntime(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSageMakerFeatureStoreRuntime(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SageMakerGeospatial\SageMakerGeospatialClient createSageMakerGeospatial(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSageMakerGeospatial(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SageMakerMetrics\SageMakerMetricsClient createSageMakerMetrics(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSageMakerMetrics(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SageMakerRuntime\SageMakerRuntimeClient createSageMakerRuntime(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSageMakerRuntime(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SagemakerEdgeManager\SagemakerEdgeManagerClient createSagemakerEdgeManager(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSagemakerEdgeManager(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SavingsPlans\SavingsPlansClient createSavingsPlans(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSavingsPlans(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Scheduler\SchedulerClient createScheduler(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionScheduler(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Schemas\SchemasClient createSchemas(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSchemas(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SecretsManager\SecretsManagerClient createSecretsManager(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSecretsManager(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SecurityHub\SecurityHubClient createSecurityHub(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSecurityHub(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SecurityLake\SecurityLakeClient createSecurityLake(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSecurityLake(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ServerlessApplicationRepository\ServerlessApplicationRepositoryClient createServerlessApplicationRepository(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionServerlessApplicationRepository(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ServiceCatalog\ServiceCatalogClient createServiceCatalog(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionServiceCatalog(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ServiceDiscovery\ServiceDiscoveryClient createServiceDiscovery(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionServiceDiscovery(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ServiceQuotas\ServiceQuotasClient createServiceQuotas(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionServiceQuotas(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Ses\SesClient createSes(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSes(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SesV2\SesV2Client createSesV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSesV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Sfn\SfnClient createSfn(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSfn(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Shield\ShieldClient createShield(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionShield(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SimSpaceWeaver\SimSpaceWeaverClient createSimSpaceWeaver(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSimSpaceWeaver(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Sms\SmsClient createSms(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSms(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SnowBall\SnowBallClient createSnowBall(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSnowBall(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SnowDeviceManagement\SnowDeviceManagementClient createSnowDeviceManagement(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSnowDeviceManagement(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Sns\SnsClient createSns(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSns(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Sqs\SqsClient createSqs(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSqs(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Ssm\SsmClient createSsm(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSsm(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SsmSap\SsmSapClient createSsmSap(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSsmSap(array $args = [])
 * @method \CloudBeds\Aws\MskFork\StorageGateway\StorageGatewayClient createStorageGateway(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionStorageGateway(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Sts\StsClient createSts(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSts(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Support\SupportClient createSupport(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSupport(array $args = [])
 * @method \CloudBeds\Aws\MskFork\SupportApp\SupportAppClient createSupportApp(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSupportApp(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Swf\SwfClient createSwf(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSwf(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Synthetics\SyntheticsClient createSynthetics(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionSynthetics(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Textract\TextractClient createTextract(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionTextract(array $args = [])
 * @method \CloudBeds\Aws\MskFork\TimestreamQuery\TimestreamQueryClient createTimestreamQuery(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionTimestreamQuery(array $args = [])
 * @method \CloudBeds\Aws\MskFork\TimestreamWrite\TimestreamWriteClient createTimestreamWrite(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionTimestreamWrite(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Tnb\TnbClient createTnb(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionTnb(array $args = [])
 * @method \CloudBeds\Aws\MskFork\TranscribeService\TranscribeServiceClient createTranscribeService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionTranscribeService(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Transfer\TransferClient createTransfer(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionTransfer(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Translate\TranslateClient createTranslate(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionTranslate(array $args = [])
 * @method \CloudBeds\Aws\MskFork\TrustedAdvisor\TrustedAdvisorClient createTrustedAdvisor(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionTrustedAdvisor(array $args = [])
 * @method \CloudBeds\Aws\MskFork\VPCLattice\VPCLatticeClient createVPCLattice(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionVPCLattice(array $args = [])
 * @method \CloudBeds\Aws\MskFork\VerifiedPermissions\VerifiedPermissionsClient createVerifiedPermissions(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionVerifiedPermissions(array $args = [])
 * @method \CloudBeds\Aws\MskFork\VoiceID\VoiceIDClient createVoiceID(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionVoiceID(array $args = [])
 * @method \CloudBeds\Aws\MskFork\WAFV2\WAFV2Client createWAFV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionWAFV2(array $args = [])
 * @method \CloudBeds\Aws\MskFork\Waf\WafClient createWaf(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionWaf(array $args = [])
 * @method \CloudBeds\Aws\MskFork\WafRegional\WafRegionalClient createWafRegional(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionWafRegional(array $args = [])
 * @method \CloudBeds\Aws\MskFork\WellArchitected\WellArchitectedClient createWellArchitected(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionWellArchitected(array $args = [])
 * @method \CloudBeds\Aws\MskFork\WorkDocs\WorkDocsClient createWorkDocs(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionWorkDocs(array $args = [])
 * @method \CloudBeds\Aws\MskFork\WorkLink\WorkLinkClient createWorkLink(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionWorkLink(array $args = [])
 * @method \CloudBeds\Aws\MskFork\WorkMail\WorkMailClient createWorkMail(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionWorkMail(array $args = [])
 * @method \CloudBeds\Aws\MskFork\WorkMailMessageFlow\WorkMailMessageFlowClient createWorkMailMessageFlow(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionWorkMailMessageFlow(array $args = [])
 * @method \CloudBeds\Aws\MskFork\WorkSpaces\WorkSpacesClient createWorkSpaces(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionWorkSpaces(array $args = [])
 * @method \CloudBeds\Aws\MskFork\WorkSpacesThinClient\WorkSpacesThinClientClient createWorkSpacesThinClient(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionWorkSpacesThinClient(array $args = [])
 * @method \CloudBeds\Aws\MskFork\WorkSpacesWeb\WorkSpacesWebClient createWorkSpacesWeb(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionWorkSpacesWeb(array $args = [])
 * @method \CloudBeds\Aws\MskFork\XRay\XRayClient createXRay(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionXRay(array $args = [])
 * @method \CloudBeds\Aws\MskFork\drs\drsClient createdrs(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegiondrs(array $args = [])
 * @method \CloudBeds\Aws\MskFork\finspace\finspaceClient createfinspace(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionfinspace(array $args = [])
 * @method \CloudBeds\Aws\MskFork\imagebuilder\imagebuilderClient createimagebuilder(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionimagebuilder(array $args = [])
 * @method \CloudBeds\Aws\MskFork\ivschat\ivschatClient createivschat(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionivschat(array $args = [])
 * @method \CloudBeds\Aws\MskFork\kendra\kendraClient createkendra(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionkendra(array $args = [])
 * @method \CloudBeds\Aws\MskFork\mgn\mgnClient createmgn(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionmgn(array $args = [])
 * @method \CloudBeds\Aws\MskFork\signer\signerClient createsigner(array $args = [])
 * @method \CloudBeds\Aws\MskFork\MultiRegionClient createMultiRegionsigner(array $args = [])
 */
class Sdk
{
    const VERSION = '3.293.5';

    /** @var array Arguments for creating clients */
    private $args;

    /**
     * Constructs a new SDK object with an associative array of default
     * client settings.
     *
     * @param array $args
     *
     * @throws \InvalidArgumentException
     * @see Aws\AwsClient::__construct for a list of available options.
     */
    public function __construct(array $args = [])
    {
        $this->args = $args;

        if (!isset($args['handler']) && !isset($args['http_handler'])) {
            $this->args['http_handler'] = default_http_handler();
        }
    }

    public function __call($name, array $args)
    {
        $args = isset($args[0]) ? $args[0] : [];
        if (strpos($name, 'createMultiRegion') === 0) {
            return $this->createMultiRegionClient(substr($name, 17), $args);
        }

        if (strpos($name, 'create') === 0) {
            return $this->createClient(substr($name, 6), $args);
        }

        throw new \BadMethodCallException("Unknown method: {$name}.");
    }

    /**
     * Get a client by name using an array of constructor options.
     *
     * @param string $name Service name or namespace (e.g., DynamoDb, s3).
     * @param array  $args Arguments to configure the client.
     *
     * @return AwsClientInterface
     * @throws \InvalidArgumentException if any required options are missing or
     *                                   the service is not supported.
     * @see Aws\AwsClient::__construct for a list of available options for args.
     */
    public function createClient($name, array $args = [])
    {
        // Get information about the service from the manifest file.
        $service = manifest($name);
        $namespace = $service['namespace'];

        // Instantiate the client class.
        $client = "Aws\\{$namespace}\\{$namespace}Client";
        return new $client($this->mergeArgs($namespace, $service, $args));
    }

    public function createMultiRegionClient($name, array $args = [])
    {
        // Get information about the service from the manifest file.
        $service = manifest($name);
        $namespace = $service['namespace'];

        $klass = "Aws\\{$namespace}\\{$namespace}MultiRegionClient";
        $klass = class_exists($klass) ? $klass : MultiRegionClient::class;

        return new $klass($this->mergeArgs($namespace, $service, $args));
    }

    /**
     * Clone existing SDK instance with ability to pass an associative array
     * of extra client settings.
     *
     * @param array $args
     *
     * @return self
     */
    public function copy(array $args = [])
    {
        return new self($args + $this->args);
    }

    private function mergeArgs($namespace, array $manifest, array $args = [])
    {
        // Merge provided args with stored, service-specific args.
        if (isset($this->args[$namespace])) {
            $args += $this->args[$namespace];
        }

        // Provide the endpoint prefix in the args.
        if (!isset($args['service'])) {
            $args['service'] = $manifest['endpoint'];
        }

        return $args + $this->args;
    }

    /**
     * Determine the endpoint prefix from a client namespace.
     *
     * @param string $name Namespace name
     *
     * @return string
     * @internal
     * @deprecated Use the `\CloudBeds\Aws\MskFork\manifest()` function instead.
     */
    public static function getEndpointPrefix($name)
    {
        return manifest($name)['endpoint'];
    }
}
